/**
 * Pre-Written Content Library — 500+ phrases for resume building
 */

export type ContentCategory = 
  | 'action-verbs'
  | 'achievements'
  | 'skills-descriptions'
  | 'tech'
  | 'finance'
  | 'healthcare'
  | 'marketing'
  | 'sales'
  | 'education'
  | 'engineering'
  | 'legal'
  | 'design'
  | 'management';

export interface ContentPhrase {
  id: string;
  text: string;
  category: ContentCategory;
  industry?: string;
  variables?: string[];
}

export const CATEGORY_LABELS: Record<ContentCategory, string> = {
  'action-verbs': 'Action Verbs',
  'achievements': 'Achievements',
  'skills-descriptions': 'Skills',
  'tech': 'Technology',
  'finance': 'Finance',
  'healthcare': 'Healthcare',
  'marketing': 'Marketing',
  'sales': 'Sales',
  'education': 'Education',
  'engineering': 'Engineering',
  'legal': 'Legal',
  'design': 'Design',
  'management': 'Management',
};

export const CATEGORY_COLORS: Record<ContentCategory, string> = {
  'action-verbs': 'bg-blue-500/20 text-blue-400',
  'achievements': 'bg-emerald-500/20 text-emerald-400',
  'skills-descriptions': 'bg-purple-500/20 text-purple-400',
  'tech': 'bg-cyan-500/20 text-cyan-400',
  'finance': 'bg-amber-500/20 text-amber-400',
  'healthcare': 'bg-rose-500/20 text-rose-400',
  'marketing': 'bg-pink-500/20 text-pink-400',
  'sales': 'bg-orange-500/20 text-orange-400',
  'education': 'bg-indigo-500/20 text-indigo-400',
  'engineering': 'bg-slate-500/20 text-slate-400',
  'legal': 'bg-stone-500/20 text-stone-400',
  'design': 'bg-fuchsia-500/20 text-fuchsia-400',
  'management': 'bg-teal-500/20 text-teal-400',
};

let _id = 0;
const p = (text: string, category: ContentCategory, industry?: string, variables?: string[]): ContentPhrase => ({
  id: `${category}-${++_id}`,
  text,
  category,
  industry,
  variables,
});

export const contentPhrases: ContentPhrase[] = [
  // ===== ACTION VERBS (200+) =====
  p('Accelerated', 'action-verbs'),
  p('Achieved', 'action-verbs'),
  p('Administered', 'action-verbs'),
  p('Advised', 'action-verbs'),
  p('Allocated', 'action-verbs'),
  p('Analyzed', 'action-verbs'),
  p('Architected', 'action-verbs'),
  p('Assembled', 'action-verbs'),
  p('Assessed', 'action-verbs'),
  p('Automated', 'action-verbs'),
  p('Balanced', 'action-verbs'),
  p('Boosted', 'action-verbs'),
  p('Bridged', 'action-verbs'),
  p('Budgeted', 'action-verbs'),
  p('Built', 'action-verbs'),
  p('Calculated', 'action-verbs'),
  p('Captured', 'action-verbs'),
  p('Centralized', 'action-verbs'),
  p('Championed', 'action-verbs'),
  p('Clarified', 'action-verbs'),
  p('Coached', 'action-verbs'),
  p('Collaborated', 'action-verbs'),
  p('Communicated', 'action-verbs'),
  p('Compiled', 'action-verbs'),
  p('Conceptualized', 'action-verbs'),
  p('Configured', 'action-verbs'),
  p('Consolidated', 'action-verbs'),
  p('Constructed', 'action-verbs'),
  p('Consulted', 'action-verbs'),
  p('Contributed', 'action-verbs'),
  p('Converted', 'action-verbs'),
  p('Coordinated', 'action-verbs'),
  p('Created', 'action-verbs'),
  p('Cultivated', 'action-verbs'),
  p('Customized', 'action-verbs'),
  p('Debugged', 'action-verbs'),
  p('Decreased', 'action-verbs'),
  p('Defined', 'action-verbs'),
  p('Delegated', 'action-verbs'),
  p('Delivered', 'action-verbs'),
  p('Demonstrated', 'action-verbs'),
  p('Deployed', 'action-verbs'),
  p('Designed', 'action-verbs'),
  p('Developed', 'action-verbs'),
  p('Devised', 'action-verbs'),
  p('Diagnosed', 'action-verbs'),
  p('Directed', 'action-verbs'),
  p('Discovered', 'action-verbs'),
  p('Documented', 'action-verbs'),
  p('Doubled', 'action-verbs'),
  p('Drove', 'action-verbs'),
  p('Earned', 'action-verbs'),
  p('Edited', 'action-verbs'),
  p('Educated', 'action-verbs'),
  p('Elevated', 'action-verbs'),
  p('Eliminated', 'action-verbs'),
  p('Empowered', 'action-verbs'),
  p('Enabled', 'action-verbs'),
  p('Encouraged', 'action-verbs'),
  p('Engineered', 'action-verbs'),
  p('Enhanced', 'action-verbs'),
  p('Ensured', 'action-verbs'),
  p('Established', 'action-verbs'),
  p('Evaluated', 'action-verbs'),
  p('Exceeded', 'action-verbs'),
  p('Executed', 'action-verbs'),
  p('Expanded', 'action-verbs'),
  p('Expedited', 'action-verbs'),
  p('Facilitated', 'action-verbs'),
  p('Finalized', 'action-verbs'),
  p('Forecasted', 'action-verbs'),
  p('Formalized', 'action-verbs'),
  p('Formulated', 'action-verbs'),
  p('Founded', 'action-verbs'),
  p('Generated', 'action-verbs'),
  p('Governed', 'action-verbs'),
  p('Guided', 'action-verbs'),
  p('Halved', 'action-verbs'),
  p('Harmonized', 'action-verbs'),
  p('Headed', 'action-verbs'),
  p('Identified', 'action-verbs'),
  p('Illustrated', 'action-verbs'),
  p('Implemented', 'action-verbs'),
  p('Improved', 'action-verbs'),
  p('Increased', 'action-verbs'),
  p('Influenced', 'action-verbs'),
  p('Initiated', 'action-verbs'),
  p('Innovated', 'action-verbs'),
  p('Inspected', 'action-verbs'),
  p('Inspired', 'action-verbs'),
  p('Installed', 'action-verbs'),
  p('Instituted', 'action-verbs'),
  p('Instructed', 'action-verbs'),
  p('Integrated', 'action-verbs'),
  p('Interpreted', 'action-verbs'),
  p('Introduced', 'action-verbs'),
  p('Invented', 'action-verbs'),
  p('Investigated', 'action-verbs'),
  p('Justified', 'action-verbs'),
  p('Launched', 'action-verbs'),
  p('Led', 'action-verbs'),
  p('Leveraged', 'action-verbs'),
  p('Liaised', 'action-verbs'),
  p('Licensed', 'action-verbs'),
  p('Maintained', 'action-verbs'),
  p('Managed', 'action-verbs'),
  p('Mapped', 'action-verbs'),
  p('Marketed', 'action-verbs'),
  p('Maximized', 'action-verbs'),
  p('Measured', 'action-verbs'),
  p('Mediated', 'action-verbs'),
  p('Mentored', 'action-verbs'),
  p('Merged', 'action-verbs'),
  p('Migrated', 'action-verbs'),
  p('Minimized', 'action-verbs'),
  p('Mobilized', 'action-verbs'),
  p('Modeled', 'action-verbs'),
  p('Modernized', 'action-verbs'),
  p('Modified', 'action-verbs'),
  p('Monitored', 'action-verbs'),
  p('Motivated', 'action-verbs'),
  p('Navigated', 'action-verbs'),
  p('Negotiated', 'action-verbs'),
  p('Obtained', 'action-verbs'),
  p('Operated', 'action-verbs'),
  p('Optimized', 'action-verbs'),
  p('Orchestrated', 'action-verbs'),
  p('Organized', 'action-verbs'),
  p('Originated', 'action-verbs'),
  p('Outpaced', 'action-verbs'),
  p('Oversaw', 'action-verbs'),
  p('Partnered', 'action-verbs'),
  p('Performed', 'action-verbs'),
  p('Pioneered', 'action-verbs'),
  p('Planned', 'action-verbs'),
  p('Positioned', 'action-verbs'),
  p('Predicted', 'action-verbs'),
  p('Prepared', 'action-verbs'),
  p('Presented', 'action-verbs'),
  p('Prioritized', 'action-verbs'),
  p('Processed', 'action-verbs'),
  p('Produced', 'action-verbs'),
  p('Programmed', 'action-verbs'),
  p('Projected', 'action-verbs'),
  p('Promoted', 'action-verbs'),
  p('Proposed', 'action-verbs'),
  p('Protected', 'action-verbs'),
  p('Proved', 'action-verbs'),
  p('Provided', 'action-verbs'),
  p('Published', 'action-verbs'),
  p('Qualified', 'action-verbs'),
  p('Raised', 'action-verbs'),
  p('Ranked', 'action-verbs'),
  p('Rebuilt', 'action-verbs'),
  p('Reconciled', 'action-verbs'),
  p('Recruited', 'action-verbs'),
  p('Redesigned', 'action-verbs'),
  p('Reduced', 'action-verbs'),
  p('Refined', 'action-verbs'),
  p('Reengineered', 'action-verbs'),
  p('Regulated', 'action-verbs'),
  p('Reinforced', 'action-verbs'),
  p('Reorganized', 'action-verbs'),
  p('Replaced', 'action-verbs'),
  p('Represented', 'action-verbs'),
  p('Researched', 'action-verbs'),
  p('Resolved', 'action-verbs'),
  p('Restructured', 'action-verbs'),
  p('Retained', 'action-verbs'),
  p('Retrieved', 'action-verbs'),
  p('Revamped', 'action-verbs'),
  p('Reviewed', 'action-verbs'),
  p('Revitalized', 'action-verbs'),
  p('Safeguarded', 'action-verbs'),
  p('Saved', 'action-verbs'),
  p('Scaled', 'action-verbs'),
  p('Scheduled', 'action-verbs'),
  p('Secured', 'action-verbs'),
  p('Shaped', 'action-verbs'),
  p('Simplified', 'action-verbs'),
  p('Solved', 'action-verbs'),
  p('Sourced', 'action-verbs'),
  p('Spearheaded', 'action-verbs'),
  p('Standardized', 'action-verbs'),
  p('Streamlined', 'action-verbs'),
  p('Strengthened', 'action-verbs'),
  p('Structured', 'action-verbs'),
  p('Supervised', 'action-verbs'),
  p('Surpassed', 'action-verbs'),
  p('Sustained', 'action-verbs'),
  p('Synthesized', 'action-verbs'),
  p('Targeted', 'action-verbs'),
  p('Tested', 'action-verbs'),
  p('Tracked', 'action-verbs'),
  p('Trained', 'action-verbs'),
  p('Transformed', 'action-verbs'),
  p('Troubleshot', 'action-verbs'),
  p('Unified', 'action-verbs'),
  p('Upgraded', 'action-verbs'),
  p('Utilized', 'action-verbs'),
  p('Validated', 'action-verbs'),
  p('Verified', 'action-verbs'),
  p('Volunteered', 'action-verbs'),
  p('Won', 'action-verbs'),

  // ===== ACHIEVEMENTS (150+) =====
  p('Increased revenue by {percentage}% within {timeframe}', 'achievements', undefined, ['percentage', 'timeframe']),
  p('Reduced costs by {percentage}% through {method}', 'achievements', undefined, ['percentage', 'method']),
  p('Led team of {number} to deliver {project} on time and under budget', 'achievements', undefined, ['number', 'project']),
  p('Grew customer base by {percentage}% year-over-year', 'achievements', undefined, ['percentage']),
  p('Achieved {percentage}% customer satisfaction rating', 'achievements', undefined, ['percentage']),
  p('Managed budget of ${amount} with zero overruns', 'achievements', undefined, ['amount']),
  p('Reduced processing time by {percentage}% through automation', 'achievements', undefined, ['percentage']),
  p('Trained and mentored {number} team members', 'achievements', undefined, ['number']),
  p('Saved ${amount} annually through process optimization', 'achievements', undefined, ['amount']),
  p('Delivered {number} projects simultaneously across multiple departments', 'achievements', undefined, ['number']),
  p('Improved team productivity by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Reduced employee turnover by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Exceeded sales targets by {percentage}% for {number} consecutive quarters', 'achievements', undefined, ['percentage', 'number']),
  p('Increased operational efficiency by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Generated ${amount} in new business revenue', 'achievements', undefined, ['amount']),
  p('Launched {number} successful products/features', 'achievements', undefined, ['number']),
  p('Reduced error rate by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Managed cross-functional team of {number} across {number} departments', 'achievements', undefined, ['number', 'number']),
  p('Automated {number} manual processes, saving {number} hours weekly', 'achievements', undefined, ['number', 'number']),
  p('Improved NPS score from {number} to {number}', 'achievements', undefined, ['number', 'number']),
  p('Reduced time-to-market by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Increased website traffic by {percentage}% through SEO optimization', 'achievements', undefined, ['percentage']),
  p('Secured {number} new enterprise clients worth ${amount}', 'achievements', undefined, ['number', 'amount']),
  p('Decreased customer churn by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Implemented new CRM system serving {number} users', 'achievements', undefined, ['number']),
  p('Streamlined onboarding process, reducing time from {number} to {number} days', 'achievements', undefined, ['number', 'number']),
  p('Achieved {percentage}% uptime for critical systems', 'achievements', undefined, ['percentage']),
  p('Resolved {number}+ customer issues with {percentage}% satisfaction', 'achievements', undefined, ['number', 'percentage']),
  p('Cut project delivery time by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Built and scaled team from {number} to {number} employees', 'achievements', undefined, ['number', 'number']),
  p('Increased conversion rate by {percentage}% through A/B testing', 'achievements', undefined, ['percentage']),
  p('Negotiated contracts saving ${amount} annually', 'achievements', undefined, ['amount']),
  p('Reduced support tickets by {percentage}% through improved documentation', 'achievements', undefined, ['percentage']),
  p('Drove {percentage}% increase in social media engagement', 'achievements', undefined, ['percentage']),
  p('Completed project {percentage}% under budget', 'achievements', undefined, ['percentage']),
  p('Processed {number}+ transactions daily with zero errors', 'achievements', undefined, ['number']),
  p('Reduced system downtime by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Increased email open rates by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Managed vendor relationships saving ${amount} annually', 'achievements', undefined, ['amount']),
  p('Improved code coverage from {percentage}% to {percentage}%', 'achievements', undefined, ['percentage', 'percentage']),
  p('Received {award} for outstanding performance', 'achievements', undefined, ['award']),
  p('Presented findings to C-suite executives and board members', 'achievements'),
  p('Published {number} research papers in peer-reviewed journals', 'achievements', undefined, ['number']),
  p('Maintained {percentage}% quality assurance pass rate', 'achievements', undefined, ['percentage']),
  p('Reduced inventory costs by {percentage}% through demand forecasting', 'achievements', undefined, ['percentage']),
  p('Facilitated {number} workshops training {number}+ employees', 'achievements', undefined, ['number', 'number']),
  p('Coordinated successful migration of {number} legacy systems', 'achievements', undefined, ['number']),
  p('Achieved ROI of {percentage}% on marketing campaigns', 'achievements', undefined, ['percentage']),
  p('Recovered ${amount} in outstanding receivables', 'achievements', undefined, ['amount']),
  p('Increased market share by {percentage}% in {timeframe}', 'achievements', undefined, ['percentage', 'timeframe']),
  p('Eliminated {number} redundant processes', 'achievements', undefined, ['number']),
  p('Won {award} recognition for innovation', 'achievements', undefined, ['award']),
  p('Improved response time from {number} hours to {number} minutes', 'achievements', undefined, ['number', 'number']),
  p('Expanded operations to {number} new markets', 'achievements', undefined, ['number']),
  p('Designed solution adopted by {number}+ organizations', 'achievements', undefined, ['number']),
  p('Reduced compliance violations by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Raised ${amount} in funding/grants', 'achievements', undefined, ['amount']),
  p('Improved retention rate by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Decreased average handling time by {percentage}%', 'achievements', undefined, ['percentage']),
  p('Delivered presentations to audiences of {number}+', 'achievements', undefined, ['number']),
  p('Grew social media following by {percentage}%', 'achievements', undefined, ['percentage']),

  // ===== SKILLS DESCRIPTIONS (100+) =====
  p('Proficient in data analysis and visualization tools', 'skills-descriptions'),
  p('Strong written and verbal communication skills', 'skills-descriptions'),
  p('Expert in project management methodologies (Agile, Scrum, Waterfall)', 'skills-descriptions'),
  p('Advanced proficiency in Microsoft Office Suite', 'skills-descriptions'),
  p('Experienced with CRM platforms (Salesforce, HubSpot)', 'skills-descriptions'),
  p('Skilled in statistical analysis and predictive modeling', 'skills-descriptions'),
  p('Proficient in cloud computing platforms (AWS, Azure, GCP)', 'skills-descriptions'),
  p('Strong leadership and team management capabilities', 'skills-descriptions'),
  p('Expert in financial modeling and forecasting', 'skills-descriptions'),
  p('Advanced knowledge of SQL and database management', 'skills-descriptions'),
  p('Experienced with CI/CD pipelines and DevOps practices', 'skills-descriptions'),
  p('Skilled in UX/UI design principles and tools', 'skills-descriptions'),
  p('Proficient in Python, JavaScript, and TypeScript', 'skills-descriptions'),
  p('Strong analytical and problem-solving abilities', 'skills-descriptions'),
  p('Expert in digital marketing and SEO strategy', 'skills-descriptions'),
  p('Advanced knowledge of machine learning algorithms', 'skills-descriptions'),
  p('Experienced with containerization (Docker, Kubernetes)', 'skills-descriptions'),
  p('Skilled in cross-functional team collaboration', 'skills-descriptions'),
  p('Proficient in business intelligence tools (Tableau, Power BI)', 'skills-descriptions'),
  p('Strong stakeholder management and presentation skills', 'skills-descriptions'),
  p('Expert in regulatory compliance and risk assessment', 'skills-descriptions'),
  p('Advanced proficiency in Adobe Creative Suite', 'skills-descriptions'),
  p('Experienced with RESTful APIs and microservices architecture', 'skills-descriptions'),
  p('Skilled in conflict resolution and negotiation', 'skills-descriptions'),
  p('Proficient in supply chain management', 'skills-descriptions'),
  p('Strong understanding of HIPAA/GDPR compliance', 'skills-descriptions'),
  p('Expert in version control systems (Git)', 'skills-descriptions'),
  p('Advanced knowledge of network security protocols', 'skills-descriptions'),
  p('Experienced with automated testing frameworks', 'skills-descriptions'),
  p('Skilled in budget planning and financial reporting', 'skills-descriptions'),
  p('Proficient in content management systems (WordPress, Drupal)', 'skills-descriptions'),
  p('Strong customer relationship management', 'skills-descriptions'),
  p('Expert in process improvement and lean methodologies', 'skills-descriptions'),
  p('Bilingual/multilingual communication abilities', 'skills-descriptions'),
  p('Advanced knowledge of ERP systems (SAP, Oracle)', 'skills-descriptions'),
  p('Experienced with A/B testing and conversion optimization', 'skills-descriptions'),
  p('Skilled in technical writing and documentation', 'skills-descriptions'),
  p('Proficient in mobile application development', 'skills-descriptions'),
  p('Strong attention to detail and quality assurance', 'skills-descriptions'),
  p('Expert in social media marketing and analytics', 'skills-descriptions'),

  // ===== TECH INDUSTRY =====
  p('Developed {number} full-stack applications using React and Node.js', 'tech', 'tech', ['number']),
  p('Architected scalable microservices handling {number}+ requests per second', 'tech', 'tech', ['number']),
  p('Reduced API response time by {percentage}% through query optimization', 'tech', 'tech', ['percentage']),
  p('Implemented CI/CD pipeline reducing deployment time from hours to minutes', 'tech', 'tech'),
  p('Migrated monolithic application to microservices architecture', 'tech', 'tech'),
  p('Built real-time data pipeline processing {number}+ events daily', 'tech', 'tech', ['number']),
  p('Designed and implemented RESTful APIs serving {number} clients', 'tech', 'tech', ['number']),
  p('Reduced cloud infrastructure costs by {percentage}% through optimization', 'tech', 'tech', ['percentage']),
  p('Achieved {percentage}% code coverage through comprehensive testing', 'tech', 'tech', ['percentage']),
  p('Led migration from on-premises to cloud infrastructure', 'tech', 'tech'),
  p('Implemented OAuth 2.0 and JWT-based authentication system', 'tech', 'tech'),
  p('Optimized database queries reducing load times by {percentage}%', 'tech', 'tech', ['percentage']),
  p('Developed mobile-responsive web application with PWA capabilities', 'tech', 'tech'),
  p('Established coding standards and code review processes', 'tech', 'tech'),
  p('Integrated third-party APIs including payment and notification services', 'tech', 'tech'),
  p('Built automated monitoring and alerting system', 'tech', 'tech'),
  p('Reduced page load time by {percentage}% through performance optimization', 'tech', 'tech', ['percentage']),
  p('Implemented serverless architecture reducing operational costs by {percentage}%', 'tech', 'tech', ['percentage']),
  p('Created reusable component library used across {number} projects', 'tech', 'tech', ['number']),
  p('Deployed containerized applications using Docker and Kubernetes', 'tech', 'tech'),

  // ===== FINANCE =====
  p('Managed portfolio of ${amount} in assets under management', 'finance', 'finance', ['amount']),
  p('Conducted financial analysis for M&A transactions valued at ${amount}', 'finance', 'finance', ['amount']),
  p('Reduced audit findings by {percentage}% through improved internal controls', 'finance', 'finance', ['percentage']),
  p('Prepared quarterly financial reports for stakeholders and board', 'finance', 'finance'),
  p('Implemented new accounting software reducing close time by {number} days', 'finance', 'finance', ['number']),
  p('Managed accounts payable/receivable processing ${amount} monthly', 'finance', 'finance', ['amount']),
  p('Developed financial models supporting ${amount} investment decisions', 'finance', 'finance', ['amount']),
  p('Ensured SOX compliance across {number} business units', 'finance', 'finance', ['number']),
  p('Reconciled {number}+ accounts monthly with {percentage}% accuracy', 'finance', 'finance', ['number', 'percentage']),
  p('Processed payroll for {number}+ employees biweekly', 'finance', 'finance', ['number']),

  // ===== HEALTHCARE =====
  p('Provided patient care for {number}+ patients daily', 'healthcare', 'healthcare', ['number']),
  p('Reduced patient wait times by {percentage}%', 'healthcare', 'healthcare', ['percentage']),
  p('Maintained {percentage}% compliance with HIPAA regulations', 'healthcare', 'healthcare', ['percentage']),
  p('Implemented electronic health record system for {number}-bed facility', 'healthcare', 'healthcare', ['number']),
  p('Coordinated care plans for {number}+ patients', 'healthcare', 'healthcare', ['number']),
  p('Reduced medication errors by {percentage}% through protocol improvements', 'healthcare', 'healthcare', ['percentage']),
  p('Trained {number} staff members on new clinical procedures', 'healthcare', 'healthcare', ['number']),
  p('Achieved {percentage}% patient satisfaction scores', 'healthcare', 'healthcare', ['percentage']),
  p('Managed clinical trials enrolling {number}+ participants', 'healthcare', 'healthcare', ['number']),
  p('Reduced hospital readmission rates by {percentage}%', 'healthcare', 'healthcare', ['percentage']),

  // ===== MARKETING =====
  p('Developed content strategy increasing organic traffic by {percentage}%', 'marketing', 'marketing', ['percentage']),
  p('Managed ${amount} annual marketing budget across {number} channels', 'marketing', 'marketing', ['amount', 'number']),
  p('Created email campaigns achieving {percentage}% open rate', 'marketing', 'marketing', ['percentage']),
  p('Increased brand awareness by {percentage}% measured by surveys', 'marketing', 'marketing', ['percentage']),
  p('Produced {number}+ pieces of content monthly (blogs, videos, infographics)', 'marketing', 'marketing', ['number']),
  p('Managed social media accounts with {number}+ combined followers', 'marketing', 'marketing', ['number']),
  p('Designed and executed influencer partnerships with {number}+ creators', 'marketing', 'marketing', ['number']),
  p('Achieved {percentage}% increase in lead generation through paid campaigns', 'marketing', 'marketing', ['percentage']),
  p('Developed brand guidelines adopted across {number} teams', 'marketing', 'marketing', ['number']),
  p('Organized {number} industry events with {number}+ attendees', 'marketing', 'marketing', ['number', 'number']),

  // ===== SALES =====
  p('Exceeded annual quota by {percentage}%, generating ${amount} in revenue', 'sales', 'sales', ['percentage', 'amount']),
  p('Built and managed pipeline of ${amount} in opportunities', 'sales', 'sales', ['amount']),
  p('Closed {number} enterprise deals with average value of ${amount}', 'sales', 'sales', ['number', 'amount']),
  p('Grew territory revenue by {percentage}% year-over-year', 'sales', 'sales', ['percentage']),
  p('Achieved top {percentage}% performer ranking company-wide', 'sales', 'sales', ['percentage']),
  p('Expanded key account revenue by {percentage}% through upselling', 'sales', 'sales', ['percentage']),
  p('Reduced sales cycle length by {percentage}% through process improvement', 'sales', 'sales', ['percentage']),
  p('Developed {number} new strategic partnerships', 'sales', 'sales', ['number']),
  p('Onboarded {number} new clients per quarter', 'sales', 'sales', ['number']),
  p('Maintained {percentage}% client retention rate', 'sales', 'sales', ['percentage']),

  // ===== EDUCATION =====
  p('Developed curriculum for {number} courses reaching {number}+ students', 'education', 'education', ['number', 'number']),
  p('Improved student test scores by {percentage}% over academic year', 'education', 'education', ['percentage']),
  p('Mentored {number} students through academic and career development', 'education', 'education', ['number']),
  p('Created online learning modules accessed by {number}+ learners', 'education', 'education', ['number']),
  p('Coordinated extracurricular programs for {number}+ students', 'education', 'education', ['number']),
  p('Implemented differentiated instruction strategies for diverse learners', 'education', 'education'),
  p('Secured ${amount} in educational grants and funding', 'education', 'education', ['amount']),
  p('Organized {number} professional development workshops for faculty', 'education', 'education', ['number']),
  p('Maintained {percentage}% student graduation rate', 'education', 'education', ['percentage']),
  p('Advised {number}+ students on course selection and career paths', 'education', 'education', ['number']),

  // ===== ENGINEERING =====
  p('Designed {number} mechanical systems meeting safety and performance standards', 'engineering', 'engineering', ['number']),
  p('Reduced manufacturing defects by {percentage}% through quality control', 'engineering', 'engineering', ['percentage']),
  p('Managed construction projects valued at ${amount}', 'engineering', 'engineering', ['amount']),
  p('Performed FEA/CFD analysis reducing prototyping costs by {percentage}%', 'engineering', 'engineering', ['percentage']),
  p('Ensured compliance with ISO 9001/14001 standards', 'engineering', 'engineering'),
  p('Optimized production line efficiency by {percentage}%', 'engineering', 'engineering', ['percentage']),
  p('Prepared technical specifications and engineering drawings', 'engineering', 'engineering'),
  p('Led root cause analysis resolving {number} critical failures', 'engineering', 'engineering', ['number']),
  p('Implemented Six Sigma methodology saving ${amount} annually', 'engineering', 'engineering', ['amount']),
  p('Supervised {number} engineers on multi-phase projects', 'engineering', 'engineering', ['number']),

  // ===== LEGAL =====
  p('Managed caseload of {number}+ matters simultaneously', 'legal', 'legal', ['number']),
  p('Drafted and reviewed {number}+ contracts and legal agreements', 'legal', 'legal', ['number']),
  p('Achieved favorable outcomes in {percentage}% of litigated cases', 'legal', 'legal', ['percentage']),
  p('Conducted due diligence for transactions valued at ${amount}', 'legal', 'legal', ['amount']),
  p('Ensured regulatory compliance across {number} jurisdictions', 'legal', 'legal', ['number']),
  p('Reduced legal spending by {percentage}% through process improvements', 'legal', 'legal', ['percentage']),
  p('Advised C-suite on corporate governance and compliance matters', 'legal', 'legal'),
  p('Prepared legal memoranda and policy recommendations', 'legal', 'legal'),
  p('Managed intellectual property portfolio of {number}+ patents/trademarks', 'legal', 'legal', ['number']),
  p('Negotiated settlements saving ${amount} in potential liabilities', 'legal', 'legal', ['amount']),

  // ===== DESIGN =====
  p('Designed user interfaces for {number}+ web and mobile applications', 'design', 'design', ['number']),
  p('Increased user engagement by {percentage}% through UX improvements', 'design', 'design', ['percentage']),
  p('Conducted {number}+ user research sessions and usability tests', 'design', 'design', ['number']),
  p('Created design system used by {number} product teams', 'design', 'design', ['number']),
  p('Reduced user task completion time by {percentage}%', 'design', 'design', ['percentage']),
  p('Designed brand identity for {number}+ clients', 'design', 'design', ['number']),
  p('Produced {number}+ marketing assets (print and digital)', 'design', 'design', ['number']),
  p('Led redesign increasing conversion rate by {percentage}%', 'design', 'design', ['percentage']),
  p('Maintained consistent design language across {number} platforms', 'design', 'design', ['number']),
  p('Created wireframes, prototypes, and high-fidelity mockups', 'design', 'design'),

  // ===== MANAGEMENT =====
  p('Directed department of {number} employees with ${amount} budget', 'management', 'management', ['number', 'amount']),
  p('Developed strategic plans resulting in {percentage}% revenue growth', 'management', 'management', ['percentage']),
  p('Implemented performance management system for {number}+ staff', 'management', 'management', ['number']),
  p('Reduced operational costs by {percentage}% while maintaining quality', 'management', 'management', ['percentage']),
  p('Led organizational restructuring improving efficiency by {percentage}%', 'management', 'management', ['percentage']),
  p('Established KPIs and reporting dashboards for executive team', 'management', 'management'),
  p('Managed vendor contracts worth ${amount} annually', 'management', 'management', ['amount']),
  p('Drove change management initiatives across {number} departments', 'management', 'management', ['number']),
  p('Hired and onboarded {number} employees in {timeframe}', 'management', 'management', ['number', 'timeframe']),
  p('Achieved {percentage}% employee satisfaction score', 'management', 'management', ['percentage']),
];

export const ALL_CATEGORIES: ContentCategory[] = Object.keys(CATEGORY_LABELS) as ContentCategory[];
