import type { ResumeExample } from '@/types/resumeExamples';

export const resumeExamples: ResumeExample[] = [
  // ===== TECHNOLOGY =====
  {
    id: 'tech-entry-1',
    title: 'Junior Frontend Developer',
    industry: 'Technology',
    experienceLevel: 'entry',
    description: 'Recent CS graduate with internship experience in React development',
    highlights: ['React & TypeScript proficiency', 'Contributed to open-source projects', 'Built accessible web apps'],
    atsScore: 88,
    templateId: 'developer',
    resumeData: {
      contactInfo: { fullName: 'Alex Chen', email: 'alex.chen@email.com', phone: '(555) 201-3456', location: 'Austin, TX', linkedin: 'linkedin.com/in/alexchen', portfolio: 'alexchen.dev' },
      summary: 'Detail-oriented frontend developer with 1+ year of experience building responsive web applications using React, TypeScript, and modern CSS frameworks. Passionate about creating accessible, performant user interfaces.',
      experience: [
        { id: '1', company: 'TechStart Inc.', position: 'Frontend Developer Intern', startDate: 'Jun 2025', endDate: 'Dec 2025', current: false, description: 'Developed and maintained customer-facing web applications', achievements: ['Built 5 reusable React component libraries adopted by 3 teams', 'Improved Lighthouse performance score from 62 to 94', 'Implemented WCAG 2.1 AA accessibility standards across the product'] },
        { id: '2', company: 'University CS Lab', position: 'Research Assistant', startDate: 'Sep 2024', endDate: 'May 2025', current: false, description: 'Assisted in web-based data visualization research', achievements: ['Created interactive D3.js dashboards for research data', 'Published findings on responsive visualization techniques'] },
      ],
      education: [{ id: '1', institution: 'University of Texas at Austin', degree: 'Bachelor of Science', field: 'Computer Science', startDate: '2021', endDate: '2025', gpa: '3.7' }],
      skills: ['React', 'TypeScript', 'JavaScript', 'HTML/CSS', 'Tailwind CSS', 'Git', 'Node.js', 'REST APIs', 'Jest', 'Figma'],
      certifications: [{ id: '1', name: 'Meta Front-End Developer Certificate', issuer: 'Meta / Coursera', date: '2025' }],
      templateId: 'developer',
    },
  },
  {
    id: 'tech-mid-1',
    title: 'Full Stack Engineer',
    industry: 'Technology',
    experienceLevel: 'mid',
    description: 'Experienced full-stack engineer with strong backend and cloud skills',
    highlights: ['Led migration to microservices', 'Reduced API latency by 40%', 'Mentored 3 junior developers'],
    atsScore: 92,
    templateId: 'modern',
    resumeData: {
      contactInfo: { fullName: 'Jordan Rivera', email: 'jordan.r@email.com', phone: '(555) 302-7890', location: 'Seattle, WA', linkedin: 'linkedin.com/in/jordanrivera' },
      summary: 'Full-stack engineer with 5 years of experience designing scalable web applications. Proven track record in React, Node.js, and AWS, with expertise in system architecture and team leadership.',
      experience: [
        { id: '1', company: 'CloudScale Technologies', position: 'Senior Full Stack Engineer', startDate: 'Mar 2024', endDate: 'Present', current: true, description: 'Lead developer on cloud-native SaaS platform', achievements: ['Architected microservices migration serving 2M+ daily users', 'Reduced API response times by 40% through Redis caching strategy', 'Mentored 3 junior developers through structured code reviews'] },
        { id: '2', company: 'DataFlow Systems', position: 'Full Stack Developer', startDate: 'Jan 2022', endDate: 'Feb 2024', current: false, description: 'Built data pipeline management tools', achievements: ['Developed real-time dashboard processing 500K events/hour', 'Implemented CI/CD pipeline reducing deployment time by 60%'] },
        { id: '3', company: 'WebCraft Agency', position: 'Junior Developer', startDate: 'Jun 2020', endDate: 'Dec 2021', current: false, description: 'Client-facing web development projects', achievements: ['Delivered 15+ client websites on time and under budget', 'Built custom CMS reducing content update time by 80%'] },
      ],
      education: [{ id: '1', institution: 'University of Washington', degree: 'Bachelor of Science', field: 'Computer Science', startDate: '2016', endDate: '2020' }],
      skills: ['React', 'Node.js', 'TypeScript', 'PostgreSQL', 'AWS', 'Docker', 'Kubernetes', 'Redis', 'GraphQL', 'CI/CD', 'System Design', 'Agile'],
      certifications: [{ id: '1', name: 'AWS Solutions Architect Associate', issuer: 'Amazon Web Services', date: '2023' }],
      templateId: 'modern',
    },
  },
  {
    id: 'tech-senior-1',
    title: 'Staff Software Engineer',
    industry: 'Technology',
    experienceLevel: 'senior',
    description: 'Staff engineer leading platform architecture at a growth-stage company',
    highlights: ['Scaled platform to 10M users', 'Led team of 8 engineers', 'Drove 99.99% uptime SLA'],
    atsScore: 95,
    templateId: 'professional',
    resumeData: {
      contactInfo: { fullName: 'Samantha Park', email: 's.park@email.com', phone: '(555) 404-5678', location: 'San Francisco, CA', linkedin: 'linkedin.com/in/sampark' },
      summary: 'Staff software engineer with 12 years of experience building and scaling distributed systems. Expert in platform architecture, technical strategy, and engineering leadership at high-growth companies.',
      experience: [
        { id: '1', company: 'ScaleUp Inc.', position: 'Staff Software Engineer', startDate: 'Jan 2023', endDate: 'Present', current: true, description: 'Technical lead for core platform team', achievements: ['Designed event-driven architecture handling 50K req/sec', 'Led cross-functional team of 8 engineers across 3 time zones', 'Achieved 99.99% uptime SLA through resilience engineering'] },
        { id: '2', company: 'MegaTech Corp', position: 'Senior Software Engineer', startDate: 'Apr 2019', endDate: 'Dec 2022', current: false, description: 'Core infrastructure and API platform', achievements: ['Scaled platform from 1M to 10M active users', 'Reduced infrastructure costs by 35% through optimization', 'Established engineering standards adopted company-wide'] },
        { id: '3', company: 'StartupHub', position: 'Software Engineer', startDate: 'Jul 2014', endDate: 'Mar 2019', current: false, description: 'Full-stack development for B2B SaaS', achievements: ['Built real-time collaboration features used by 500K+ users', 'Implemented automated testing reducing production bugs by 70%'] },
      ],
      education: [{ id: '1', institution: 'Stanford University', degree: 'Master of Science', field: 'Computer Science', startDate: '2012', endDate: '2014' }, { id: '2', institution: 'UC Berkeley', degree: 'Bachelor of Science', field: 'EECS', startDate: '2008', endDate: '2012' }],
      skills: ['System Design', 'Distributed Systems', 'Go', 'Python', 'Kubernetes', 'AWS', 'PostgreSQL', 'Kafka', 'gRPC', 'Technical Leadership', 'Architecture'],
      certifications: [],
      templateId: 'professional',
    },
  },
  // ===== MARKETING/SALES =====
  {
    id: 'marketing-entry-1',
    title: 'Marketing Coordinator',
    industry: 'Marketing/Sales',
    experienceLevel: 'entry',
    description: 'Creative marketing graduate with strong social media and content skills',
    highlights: ['Grew social following by 200%', 'Created viral content campaigns', 'Google Analytics certified'],
    atsScore: 85,
    templateId: 'marketing',
    resumeData: {
      contactInfo: { fullName: 'Maya Johnson', email: 'maya.j@email.com', phone: '(555) 505-1234', location: 'Chicago, IL' },
      summary: 'Creative marketing coordinator with expertise in social media strategy, content creation, and digital campaigns. Proven ability to grow brand awareness and engagement through data-driven marketing initiatives.',
      experience: [
        { id: '1', company: 'BrandBuzz Agency', position: 'Marketing Coordinator', startDate: 'Jan 2025', endDate: 'Present', current: true, description: 'Managed social media and content for 8 clients', achievements: ['Grew combined social following by 200% across platforms', 'Created content calendar generating 45% more engagement', 'Managed $50K monthly ad budget with 3.2x ROAS'] },
        { id: '2', company: 'Local Coffee Co.', position: 'Social Media Intern', startDate: 'May 2024', endDate: 'Dec 2024', current: false, description: 'Built social presence from scratch', achievements: ['Launched TikTok account reaching 10K followers in 3 months', 'Designed email campaigns with 28% open rate'] },
      ],
      education: [{ id: '1', institution: 'Northwestern University', degree: 'Bachelor of Arts', field: 'Marketing', startDate: '2020', endDate: '2024' }],
      skills: ['Social Media Marketing', 'Content Strategy', 'Google Analytics', 'SEO/SEM', 'Canva', 'Adobe Creative Suite', 'Email Marketing', 'Copywriting', 'HubSpot', 'A/B Testing'],
      certifications: [{ id: '1', name: 'Google Analytics Certification', issuer: 'Google', date: '2024' }, { id: '2', name: 'HubSpot Content Marketing', issuer: 'HubSpot Academy', date: '2024' }],
      templateId: 'marketing',
    },
  },
  {
    id: 'sales-mid-1',
    title: 'Account Executive',
    industry: 'Marketing/Sales',
    experienceLevel: 'mid',
    description: 'Results-driven sales professional consistently exceeding quota',
    highlights: ['150% quota attainment', 'Closed $2.5M annual deals', 'Built 200+ client relationships'],
    atsScore: 90,
    templateId: 'sales',
    resumeData: {
      contactInfo: { fullName: 'Marcus Thompson', email: 'marcus.t@email.com', phone: '(555) 606-7890', location: 'New York, NY' },
      summary: 'Results-driven account executive with 5 years in B2B SaaS sales. Consistently exceeds quota through consultative selling, strategic pipeline management, and deep client relationship building.',
      experience: [
        { id: '1', company: 'SalesForce Pro', position: 'Senior Account Executive', startDate: 'Feb 2024', endDate: 'Present', current: true, description: 'Enterprise SaaS sales for mid-market accounts', achievements: ['Achieved 150% of annual quota ($2.5M ARR)', 'Built pipeline of 200+ qualified opportunities', 'Won "Top Performer" award Q3 2024 and Q1 2025'] },
        { id: '2', company: 'GrowthTech Solutions', position: 'Account Executive', startDate: 'Jun 2021', endDate: 'Jan 2024', current: false, description: 'SMB and mid-market sales', achievements: ['Closed $1.8M in new business in first year', 'Maintained 95% client retention rate', 'Developed sales playbook adopted by 15-person team'] },
      ],
      education: [{ id: '1', institution: 'New York University', degree: 'Bachelor of Science', field: 'Business Administration', startDate: '2017', endDate: '2021' }],
      skills: ['Consultative Selling', 'Pipeline Management', 'Salesforce CRM', 'Contract Negotiation', 'Cold Outreach', 'Account Management', 'Presentation Skills', 'Forecasting', 'Cross-selling'],
      certifications: [{ id: '1', name: 'Sandler Sales Certification', issuer: 'Sandler Training', date: '2023' }],
      templateId: 'sales',
    },
  },
  // ===== HEALTHCARE =====
  {
    id: 'healthcare-entry-1',
    title: 'Registered Nurse',
    industry: 'Healthcare',
    experienceLevel: 'entry',
    description: 'Compassionate RN with acute care experience',
    highlights: ['BSN with honors', 'ICU rotation experience', 'BLS & ACLS certified'],
    atsScore: 87,
    templateId: 'healthcare',
    resumeData: {
      contactInfo: { fullName: 'Emily Nguyen', email: 'e.nguyen@email.com', phone: '(555) 707-2345', location: 'Denver, CO' },
      summary: 'Compassionate registered nurse with BSN and clinical experience in acute care, emergency, and ICU settings. Committed to evidence-based practice and patient-centered care.',
      experience: [
        { id: '1', company: 'Denver General Hospital', position: 'Registered Nurse - Med/Surg', startDate: 'Jul 2025', endDate: 'Present', current: true, description: 'Providing direct patient care in 36-bed medical-surgical unit', achievements: ['Managed care for 5-6 patients per shift with zero medication errors', 'Implemented fall prevention protocol reducing incidents by 30%', 'Trained 4 new graduate nurses during orientation'] },
        { id: '2', company: 'Rocky Mountain Medical Center', position: 'Nurse Extern', startDate: 'Jan 2025', endDate: 'Jun 2025', current: false, description: 'Clinical externship in emergency department', achievements: ['Assisted with 200+ patient assessments and triage decisions', 'Gained proficiency in IV insertion, wound care, and ECG monitoring'] },
      ],
      education: [{ id: '1', institution: 'University of Colorado', degree: 'Bachelor of Science', field: 'Nursing (BSN)', startDate: '2021', endDate: '2025', gpa: '3.8' }],
      skills: ['Patient Assessment', 'Medication Administration', 'IV Therapy', 'EMR (Epic)', 'Wound Care', 'Patient Education', 'Vital Signs Monitoring', 'Infection Control', 'Team Collaboration'],
      certifications: [{ id: '1', name: 'Registered Nurse License', issuer: 'Colorado State Board of Nursing', date: '2025' }, { id: '2', name: 'BLS & ACLS', issuer: 'American Heart Association', date: '2025' }],
      templateId: 'healthcare',
    },
  },
  {
    id: 'healthcare-senior-1',
    title: 'Nurse Practitioner',
    industry: 'Healthcare',
    experienceLevel: 'senior',
    description: 'Experienced family NP with 10+ years in primary care',
    highlights: ['Managed 2,000+ patient panel', 'Published clinical research', '98% patient satisfaction'],
    atsScore: 91,
    templateId: 'healthcare',
    resumeData: {
      contactInfo: { fullName: 'Dr. Rachel Kim', email: 'r.kim@email.com', phone: '(555) 808-6789', location: 'Portland, OR' },
      summary: 'Board-certified Family Nurse Practitioner with 10+ years of experience in primary care. Expertise in chronic disease management, preventive care, and patient education with consistently high satisfaction scores.',
      experience: [
        { id: '1', company: 'Pacific Health Partners', position: 'Family Nurse Practitioner', startDate: 'Mar 2020', endDate: 'Present', current: true, description: 'Autonomous primary care provider', achievements: ['Managed panel of 2,000+ patients across all age groups', 'Achieved 98% patient satisfaction rating', 'Implemented diabetes management program reducing A1C by average 1.5%'] },
        { id: '2', company: 'Community Health Clinic', position: 'Family Nurse Practitioner', startDate: 'Aug 2016', endDate: 'Feb 2020', current: false, description: 'Underserved community primary care', achievements: ['Provided care to 1,500+ uninsured patients annually', 'Established telehealth program serving rural communities', 'Published research on health disparities in primary care'] },
      ],
      education: [{ id: '1', institution: 'Oregon Health & Science University', degree: 'Doctor of Nursing Practice', field: 'Family Practice', startDate: '2014', endDate: '2016' }, { id: '2', institution: 'University of Portland', degree: 'Bachelor of Science', field: 'Nursing', startDate: '2008', endDate: '2012' }],
      skills: ['Primary Care', 'Chronic Disease Management', 'Patient Education', 'Clinical Research', 'Telehealth', 'EMR Systems', 'Preventive Care', 'Team Leadership', 'Quality Improvement'],
      certifications: [{ id: '1', name: 'FNP-BC Certification', issuer: 'AANP', date: '2016' }, { id: '2', name: 'DEA License', issuer: 'DEA', date: '2016' }],
      templateId: 'healthcare',
    },
  },
  // ===== FINANCE =====
  {
    id: 'finance-mid-1',
    title: 'Financial Analyst',
    industry: 'Finance',
    experienceLevel: 'mid',
    description: 'CFA candidate with strong modeling and analysis skills',
    highlights: ['Built models saving $3M annually', 'CFA Level II candidate', 'Advanced Excel & Python'],
    atsScore: 93,
    templateId: 'banking',
    resumeData: {
      contactInfo: { fullName: 'David Park', email: 'd.park@email.com', phone: '(555) 909-3456', location: 'Boston, MA' },
      summary: 'Detail-oriented financial analyst with 4 years of experience in corporate finance, financial modeling, and strategic analysis. CFA Level II candidate with expertise in forecasting and valuation.',
      experience: [
        { id: '1', company: 'Beacon Capital Partners', position: 'Senior Financial Analyst', startDate: 'Apr 2024', endDate: 'Present', current: true, description: 'Corporate finance and strategic planning', achievements: ['Built DCF and LBO models for $500M+ acquisition targets', 'Identified cost optimization opportunities saving $3M annually', 'Automated monthly reporting reducing preparation time by 65%'] },
        { id: '2', company: 'Northeast Bank', position: 'Financial Analyst', startDate: 'Jul 2022', endDate: 'Mar 2024', current: false, description: 'Credit analysis and portfolio management', achievements: ['Analyzed 50+ credit applications totaling $200M', 'Developed risk scoring model improving default prediction by 25%'] },
      ],
      education: [{ id: '1', institution: 'Boston University', degree: 'Bachelor of Science', field: 'Finance', startDate: '2018', endDate: '2022', gpa: '3.6' }],
      skills: ['Financial Modeling', 'DCF Analysis', 'Excel (Advanced)', 'Python', 'SQL', 'Bloomberg Terminal', 'PowerPoint', 'Forecasting', 'Risk Analysis', 'Tableau'],
      certifications: [{ id: '1', name: 'CFA Level II Candidate', issuer: 'CFA Institute', date: '2025' }, { id: '2', name: 'Financial Modeling Certificate', issuer: 'Wall Street Prep', date: '2023' }],
      templateId: 'banking',
    },
  },
  {
    id: 'finance-executive-1',
    title: 'Chief Financial Officer',
    industry: 'Finance',
    experienceLevel: 'executive',
    description: 'C-suite finance leader with IPO and M&A experience',
    highlights: ['Led successful IPO ($500M)', 'Managed $2B budget', '20+ years experience'],
    atsScore: 94,
    templateId: 'executive',
    resumeData: {
      contactInfo: { fullName: 'Robert Chen', email: 'r.chen@email.com', phone: '(555) 110-4567', location: 'New York, NY' },
      summary: 'Transformational CFO with 20+ years of experience in strategic finance, capital markets, and operational leadership. Led IPO process, multiple M&A transactions, and enterprise-wide digital transformation initiatives.',
      experience: [
        { id: '1', company: 'TechGrowth Corp', position: 'Chief Financial Officer', startDate: 'Jan 2020', endDate: 'Present', current: true, description: 'C-suite financial leadership for $800M revenue company', achievements: ['Led successful IPO raising $500M at $4B valuation', 'Managed $2B annual budget across 5 business units', 'Drove 40% revenue growth through strategic acquisitions'] },
        { id: '2', company: 'GlobalFinance Inc.', position: 'VP of Finance', startDate: 'Mar 2014', endDate: 'Dec 2019', current: false, description: 'Finance leadership for global operations', achievements: ['Oversaw $1.2B annual budget and 50-person finance team', 'Completed 3 M&A transactions totaling $800M', 'Implemented ERP system saving $15M in operational costs'] },
      ],
      education: [{ id: '1', institution: 'Wharton School, UPenn', degree: 'MBA', field: 'Finance', startDate: '2002', endDate: '2004' }, { id: '2', institution: 'Yale University', degree: 'Bachelor of Arts', field: 'Economics', startDate: '1998', endDate: '2002' }],
      skills: ['Strategic Finance', 'IPO Management', 'M&A', 'Capital Markets', 'Board Relations', 'P&L Management', 'Financial Planning', 'Risk Management', 'Investor Relations', 'Team Leadership'],
      certifications: [{ id: '1', name: 'CPA', issuer: 'AICPA', date: '2006' }],
      templateId: 'executive',
    },
  },
  // ===== EDUCATION =====
  {
    id: 'education-mid-1',
    title: 'High School Teacher',
    industry: 'Education',
    experienceLevel: 'mid',
    description: 'Engaging STEM teacher with curriculum development expertise',
    highlights: ['95% student pass rate', 'Launched robotics club', 'State teaching award recipient'],
    atsScore: 86,
    templateId: 'academic',
    resumeData: {
      contactInfo: { fullName: 'Lisa Martinez', email: 'l.martinez@email.com', phone: '(555) 212-5678', location: 'Phoenix, AZ' },
      summary: 'Dedicated high school science teacher with 6 years of experience inspiring students through hands-on STEM education. Expert in differentiated instruction, curriculum development, and extracurricular program leadership.',
      experience: [
        { id: '1', company: 'Desert Ridge High School', position: 'Science Teacher', startDate: 'Aug 2021', endDate: 'Present', current: true, description: 'Teaching AP Biology and Chemistry to 150+ students annually', achievements: ['Achieved 95% pass rate on AP Biology exam (vs 65% national avg)', 'Founded robotics club growing to 40 members in 2 years', 'Received Arizona STEM Teacher of the Year nomination 2024'] },
        { id: '2', company: 'Sunrise Middle School', position: 'Science Teacher', startDate: 'Aug 2019', endDate: 'Jul 2021', current: false, description: 'Middle school life science and earth science', achievements: ['Developed project-based curriculum increasing student engagement by 40%', 'Mentored 5 student teachers through practicum placements'] },
      ],
      education: [{ id: '1', institution: 'Arizona State University', degree: 'Master of Education', field: 'Curriculum & Instruction', startDate: '2019', endDate: '2021' }, { id: '2', institution: 'University of Arizona', degree: 'Bachelor of Science', field: 'Biology', startDate: '2015', endDate: '2019' }],
      skills: ['Curriculum Development', 'Differentiated Instruction', 'STEM Education', 'Classroom Management', 'Google Classroom', 'Project-Based Learning', 'Assessment Design', 'Student Mentoring', 'Parent Communication'],
      certifications: [{ id: '1', name: 'Arizona Teaching Certificate', issuer: 'AZ Dept of Education', date: '2019' }, { id: '2', name: 'AP Biology Certification', issuer: 'College Board', date: '2021' }],
      templateId: 'academic',
    },
  },
  // ===== CREATIVE/DESIGN =====
  {
    id: 'design-mid-1',
    title: 'UX/UI Designer',
    industry: 'Creative/Design',
    experienceLevel: 'mid',
    description: 'User-centered designer with strong research and prototyping skills',
    highlights: ['Redesigned app boosting retention 35%', 'Led design system creation', 'Conducted 100+ user interviews'],
    atsScore: 84,
    templateId: 'designer',
    resumeData: {
      contactInfo: { fullName: 'Sarah Kim', email: 's.kim@email.com', phone: '(555) 313-6789', location: 'Los Angeles, CA', portfolio: 'sarahkim.design' },
      summary: 'UX/UI designer with 5 years of experience creating intuitive digital products. Combines user research, prototyping, and visual design to deliver experiences that drive engagement and business results.',
      experience: [
        { id: '1', company: 'DesignLab Studio', position: 'Senior UX Designer', startDate: 'May 2023', endDate: 'Present', current: true, description: 'Lead designer for consumer mobile applications', achievements: ['Redesigned onboarding flow increasing user retention by 35%', 'Created comprehensive design system with 200+ components', 'Conducted 100+ user interviews and usability tests'] },
        { id: '2', company: 'AppWorks Inc.', position: 'UX/UI Designer', startDate: 'Mar 2021', endDate: 'Apr 2023', current: false, description: 'Mobile and web application design', achievements: ['Designed 3 mobile apps from concept to App Store launch', 'Improved task completion rate by 45% through UX optimization'] },
      ],
      education: [{ id: '1', institution: 'ArtCenter College of Design', degree: 'Bachelor of Fine Arts', field: 'Interaction Design', startDate: '2017', endDate: '2021' }],
      skills: ['Figma', 'User Research', 'Prototyping', 'Design Systems', 'Wireframing', 'Usability Testing', 'Adobe Creative Suite', 'Responsive Design', 'Accessibility', 'Motion Design'],
      certifications: [{ id: '1', name: 'Google UX Design Certificate', issuer: 'Google', date: '2022' }],
      templateId: 'designer',
    },
  },
  // ===== ENGINEERING =====
  {
    id: 'engineering-mid-1',
    title: 'Mechanical Engineer',
    industry: 'Engineering',
    experienceLevel: 'mid',
    description: 'PE-licensed mechanical engineer specializing in product design',
    highlights: ['Designed products generating $10M revenue', 'PE licensed', 'Led 5 product launches'],
    atsScore: 89,
    templateId: 'professional',
    resumeData: {
      contactInfo: { fullName: 'James Wilson', email: 'j.wilson@email.com', phone: '(555) 414-7890', location: 'Detroit, MI' },
      summary: 'Licensed Professional Engineer with 6 years of experience in mechanical design, product development, and manufacturing optimization. Expert in CAD modeling, FEA analysis, and cross-functional project management.',
      experience: [
        { id: '1', company: 'AutoParts Manufacturing', position: 'Senior Mechanical Engineer', startDate: 'Jun 2023', endDate: 'Present', current: true, description: 'Lead engineer for automotive component design', achievements: ['Designed 3 product lines generating $10M in annual revenue', 'Reduced manufacturing defects by 28% through DFM analysis', 'Led cross-functional team of 12 through 5 successful product launches'] },
        { id: '2', company: 'PrecisionTech Co.', position: 'Mechanical Engineer', startDate: 'Aug 2020', endDate: 'May 2023', current: false, description: 'Product design and testing', achievements: ['Created 50+ detailed CAD assemblies using SolidWorks', 'Conducted FEA simulations reducing physical prototype iterations by 40%'] },
      ],
      education: [{ id: '1', institution: 'University of Michigan', degree: 'Master of Science', field: 'Mechanical Engineering', startDate: '2018', endDate: '2020' }, { id: '2', institution: 'Michigan State University', degree: 'Bachelor of Science', field: 'Mechanical Engineering', startDate: '2014', endDate: '2018' }],
      skills: ['SolidWorks', 'AutoCAD', 'ANSYS FEA', 'GD&T', 'DFM/DFA', 'Project Management', 'Product Development', '3D Printing', 'Lean Manufacturing', 'Technical Documentation'],
      certifications: [{ id: '1', name: 'Professional Engineer (PE)', issuer: 'Michigan Board of PE', date: '2023' }, { id: '2', name: 'Six Sigma Green Belt', issuer: 'ASQ', date: '2022' }],
      templateId: 'professional',
    },
  },
  // ===== CUSTOMER SERVICE =====
  {
    id: 'cs-entry-1',
    title: 'Customer Success Associate',
    industry: 'Customer Service',
    experienceLevel: 'entry',
    description: 'Enthusiastic customer success professional with SaaS experience',
    highlights: ['97% CSAT score', 'Resolved 500+ tickets/month', 'Reduced churn by 15%'],
    atsScore: 83,
    templateId: 'clean',
    resumeData: {
      contactInfo: { fullName: 'Ashley Brown', email: 'a.brown@email.com', phone: '(555) 515-8901', location: 'Nashville, TN' },
      summary: 'Customer-focused success associate with 2 years of experience in SaaS customer support and relationship management. Known for high satisfaction scores and proactive problem-solving.',
      experience: [
        { id: '1', company: 'SaaS Solutions Co.', position: 'Customer Success Associate', startDate: 'Mar 2024', endDate: 'Present', current: true, description: 'Managing portfolio of 80+ SMB accounts', achievements: ['Maintained 97% CSAT score across 500+ monthly interactions', 'Reduced customer churn by 15% through proactive outreach program', 'Created 20+ help center articles reducing ticket volume by 25%'] },
        { id: '2', company: 'RetailPlus', position: 'Customer Service Representative', startDate: 'Jun 2023', endDate: 'Feb 2024', current: false, description: 'Frontline customer support', achievements: ['Handled 50+ daily customer inquiries via phone, email, and chat', 'Consistently ranked in top 10% for customer satisfaction'] },
      ],
      education: [{ id: '1', institution: 'Vanderbilt University', degree: 'Bachelor of Arts', field: 'Communications', startDate: '2019', endDate: '2023' }],
      skills: ['Customer Success', 'Zendesk', 'Intercom', 'CRM Management', 'Onboarding', 'Problem Solving', 'Communication', 'Data Analysis', 'Product Knowledge', 'Upselling'],
      certifications: [],
      templateId: 'clean',
    },
  },
  // ===== MANAGEMENT/EXECUTIVE =====
  {
    id: 'mgmt-senior-1',
    title: 'Director of Operations',
    industry: 'Management/Executive',
    experienceLevel: 'senior',
    description: 'Operations leader driving efficiency and growth across organizations',
    highlights: ['Managed $50M budget', 'Led 200+ person team', 'Reduced costs by 30%'],
    atsScore: 92,
    templateId: 'corporate',
    resumeData: {
      contactInfo: { fullName: 'Michael Zhang', email: 'm.zhang@email.com', phone: '(555) 616-0123', location: 'Dallas, TX' },
      summary: 'Strategic operations director with 12 years of experience optimizing business processes, managing large teams, and driving organizational growth. Proven track record of reducing costs while improving quality and efficiency.',
      experience: [
        { id: '1', company: 'Enterprise Solutions Group', position: 'Director of Operations', startDate: 'Feb 2021', endDate: 'Present', current: true, description: 'Overseeing operations for $200M revenue division', achievements: ['Managed $50M operational budget with consistent under-budget performance', 'Led transformation initiative reducing operational costs by 30%', 'Built and managed team of 200+ across 4 regional offices'] },
        { id: '2', company: 'National Logistics Corp', position: 'Senior Operations Manager', startDate: 'Jul 2016', endDate: 'Jan 2021', current: false, description: 'Multi-site operations management', achievements: ['Improved supply chain efficiency by 40% through process redesign', 'Implemented Lean Six Sigma saving $8M annually', 'Achieved ISO 9001 certification for all 3 facilities'] },
      ],
      education: [{ id: '1', institution: 'University of Texas at Dallas', degree: 'MBA', field: 'Operations Management', startDate: '2014', endDate: '2016' }, { id: '2', institution: 'Texas A&M University', degree: 'Bachelor of Science', field: 'Industrial Engineering', startDate: '2008', endDate: '2012' }],
      skills: ['Operations Strategy', 'P&L Management', 'Team Leadership', 'Lean Six Sigma', 'Process Optimization', 'Budget Management', 'Vendor Management', 'Change Management', 'KPI Development', 'Strategic Planning'],
      certifications: [{ id: '1', name: 'Lean Six Sigma Black Belt', issuer: 'ASQ', date: '2018' }, { id: '2', name: 'PMP', issuer: 'PMI', date: '2017' }],
      templateId: 'corporate',
    },
  },
  {
    id: 'mgmt-executive-1',
    title: 'Chief Executive Officer',
    industry: 'Management/Executive',
    experienceLevel: 'executive',
    description: 'Visionary CEO who scaled startups to enterprise companies',
    highlights: ['Scaled company from $5M to $200M', 'Led team of 500+', 'Raised $100M in funding'],
    atsScore: 96,
    templateId: 'executive',
    resumeData: {
      contactInfo: { fullName: 'Catherine Williams', email: 'c.williams@email.com', phone: '(555) 717-1234', location: 'San Francisco, CA' },
      summary: 'Visionary technology executive with 18+ years of experience scaling companies from startup to enterprise. Proven ability to raise capital, build world-class teams, and drive market-defining innovation.',
      experience: [
        { id: '1', company: 'InnovateTech Inc.', position: 'Chief Executive Officer', startDate: 'Jan 2019', endDate: 'Present', current: true, description: 'Leading enterprise SaaS company', achievements: ['Scaled revenue from $5M to $200M ARR in 5 years', 'Raised $100M Series C at $1.5B valuation', 'Grew team from 50 to 500+ employees across 8 countries'] },
        { id: '2', company: 'DisruptCo', position: 'COO / Co-Founder', startDate: 'Mar 2013', endDate: 'Dec 2018', current: false, description: 'Co-founded and scaled B2B marketplace', achievements: ['Built company to $40M ARR and successful acquisition', 'Established operations across 3 continents', 'Named to Forbes "40 Under 40" list'] },
      ],
      education: [{ id: '1', institution: 'Harvard Business School', degree: 'MBA', field: 'General Management', startDate: '2009', endDate: '2011' }, { id: '2', institution: 'MIT', degree: 'Bachelor of Science', field: 'Computer Science', startDate: '2003', endDate: '2007' }],
      skills: ['Strategic Vision', 'Capital Raising', 'Board Management', 'M&A', 'Go-to-Market Strategy', 'Organizational Design', 'Public Speaking', 'Investor Relations', 'P&L Ownership', 'Culture Building'],
      certifications: [],
      templateId: 'executive',
    },
  },
  // ===== HR/RECRUITING =====
  {
    id: 'hr-mid-1',
    title: 'HR Business Partner',
    industry: 'HR/Recruiting',
    experienceLevel: 'mid',
    description: 'Strategic HRBP aligning people strategy with business goals',
    highlights: ['Reduced turnover by 25%', 'Led DEIB initiatives', 'Supported 300+ employees'],
    atsScore: 88,
    templateId: 'classic',
    resumeData: {
      contactInfo: { fullName: 'Nicole Adams', email: 'n.adams@email.com', phone: '(555) 818-2345', location: 'Atlanta, GA' },
      summary: 'Strategic HR Business Partner with 5 years of experience aligning people strategy with business objectives. Expert in talent management, employee relations, and organizational development.',
      experience: [
        { id: '1', company: 'TechForward Inc.', position: 'HR Business Partner', startDate: 'Apr 2023', endDate: 'Present', current: true, description: 'Strategic HR partner for engineering and product divisions', achievements: ['Reduced voluntary turnover by 25% through retention program', 'Led DEIB task force increasing diverse hiring by 40%', 'Supported 300+ employees across 3 business units'] },
        { id: '2', company: 'PeopleFirst Consulting', position: 'HR Generalist', startDate: 'Jul 2021', endDate: 'Mar 2023', current: false, description: 'Full-cycle HR for mid-size clients', achievements: ['Managed full-cycle recruiting for 100+ positions annually', 'Implemented HRIS system streamlining processes for 5 client companies'] },
      ],
      education: [{ id: '1', institution: 'Emory University', degree: 'Master of Science', field: 'Human Resources Management', startDate: '2019', endDate: '2021' }],
      skills: ['Talent Management', 'Employee Relations', 'HRIS (Workday)', 'Performance Management', 'DEIB', 'Compensation & Benefits', 'Organizational Development', 'Labor Law', 'Change Management', 'Coaching'],
      certifications: [{ id: '1', name: 'SHRM-CP', issuer: 'SHRM', date: '2022' }],
      templateId: 'classic',
    },
  },
  // ===== LEGAL =====
  {
    id: 'legal-mid-1',
    title: 'Corporate Attorney',
    industry: 'Legal',
    experienceLevel: 'mid',
    description: 'Corporate attorney specializing in M&A and securities',
    highlights: ['Closed $2B+ in transactions', 'Published in law review', 'Bar admitted in 3 states'],
    atsScore: 90,
    templateId: 'legal',
    resumeData: {
      contactInfo: { fullName: 'Jonathan Harris', email: 'j.harris@email.com', phone: '(555) 919-3456', location: 'Washington, DC' },
      summary: 'Corporate attorney with 6 years of experience in mergers & acquisitions, securities law, and corporate governance. Proven track record of closing complex transactions and advising Fortune 500 clients.',
      experience: [
        { id: '1', company: 'Sullivan & Parker LLP', position: 'Senior Associate', startDate: 'Sep 2022', endDate: 'Present', current: true, description: 'Corporate M&A practice group', achievements: ['Led legal due diligence for $2B+ in M&A transactions', 'Advised 15+ public company boards on governance matters', 'Published article in Harvard Law Review on SEC regulations'] },
        { id: '2', company: 'Davis Wright LLP', position: 'Associate Attorney', startDate: 'Sep 2019', endDate: 'Aug 2022', current: false, description: 'Corporate and securities practice', achievements: ['Drafted and negotiated 50+ commercial agreements', 'Managed SEC filings for 8 publicly traded clients'] },
      ],
      education: [{ id: '1', institution: 'Georgetown University Law Center', degree: 'Juris Doctor', field: 'Law', startDate: '2016', endDate: '2019', gpa: '3.7' }, { id: '2', institution: 'Duke University', degree: 'Bachelor of Arts', field: 'Political Science', startDate: '2012', endDate: '2016' }],
      skills: ['M&A', 'Securities Law', 'Corporate Governance', 'Due Diligence', 'Contract Negotiation', 'SEC Compliance', 'Legal Research', 'Westlaw', 'Client Advisory', 'Legal Writing'],
      certifications: [{ id: '1', name: 'Bar Admission - DC, NY, VA', issuer: 'State Bar', date: '2019' }],
      templateId: 'legal',
    },
  },
  // ===== HOSPITALITY =====
  {
    id: 'hospitality-entry-1',
    title: 'Hotel Front Desk Manager',
    industry: 'Hospitality',
    experienceLevel: 'entry',
    description: 'Hospitality professional with luxury hotel experience',
    highlights: ['4.9/5 guest satisfaction', 'Managed team of 8', 'Increased upsell revenue 20%'],
    atsScore: 82,
    templateId: 'elegant',
    resumeData: {
      contactInfo: { fullName: 'Maria Santos', email: 'm.santos@email.com', phone: '(555) 020-4567', location: 'Miami, FL' },
      summary: 'Hospitality professional with 2 years of experience in luxury hotel operations. Passionate about creating exceptional guest experiences through attentive service and efficient operations.',
      experience: [
        { id: '1', company: 'The Grand Resort & Spa', position: 'Front Desk Supervisor', startDate: 'Jun 2024', endDate: 'Present', current: true, description: 'Supervising front desk operations at 300-room luxury resort', achievements: ['Maintained 4.9/5 average guest satisfaction score', 'Supervised team of 8 front desk agents across 3 shifts', 'Increased room upgrade upsell revenue by 20%'] },
        { id: '2', company: 'Seaside Boutique Hotel', position: 'Front Desk Agent', startDate: 'Aug 2023', endDate: 'May 2024', current: false, description: 'Guest services and reservations', achievements: ['Processed 100+ check-ins/check-outs daily with zero complaints', 'Resolved guest issues with 98% first-contact resolution rate'] },
      ],
      education: [{ id: '1', institution: 'Florida International University', degree: 'Bachelor of Science', field: 'Hospitality Management', startDate: '2019', endDate: '2023' }],
      skills: ['Guest Relations', 'Opera PMS', 'Revenue Management', 'Team Leadership', 'Conflict Resolution', 'Upselling', 'Multilingual (English/Spanish/Portuguese)', 'Event Coordination', 'Quality Assurance'],
      certifications: [{ id: '1', name: 'Certified Hospitality Supervisor', issuer: 'AHLEI', date: '2024' }],
      templateId: 'elegant',
    },
  },
  // ===== ADDITIONAL EXAMPLES FOR COVERAGE =====
  {
    id: 'tech-executive-1',
    title: 'VP of Engineering',
    industry: 'Technology',
    experienceLevel: 'executive',
    description: 'Engineering executive building high-performing teams at scale',
    highlights: ['Built engineering org to 150+', 'Delivered $100M product line', 'IPO contributor'],
    atsScore: 93,
    templateId: 'corporate',
    resumeData: {
      contactInfo: { fullName: 'Thomas Lee', email: 't.lee@email.com', phone: '(555) 121-5678', location: 'Palo Alto, CA' },
      summary: 'Engineering executive with 15+ years of experience building and scaling world-class engineering organizations. Track record of delivering products that generate $100M+ revenue and leading through hypergrowth.',
      experience: [
        { id: '1', company: 'CloudNova Systems', position: 'VP of Engineering', startDate: 'Mar 2021', endDate: 'Present', current: true, description: 'Leading all engineering for cloud infrastructure platform', achievements: ['Grew engineering organization from 30 to 150+ engineers', 'Delivered cloud platform generating $100M ARR', 'Contributed to successful IPO process and S-1 preparation'] },
        { id: '2', company: 'RapidScale Inc.', position: 'Senior Director of Engineering', startDate: 'Jan 2017', endDate: 'Feb 2021', current: false, description: 'Platform engineering leadership', achievements: ['Led 80-person engineering team across 4 product lines', 'Reduced time-to-market by 50% through agile transformation', 'Established SRE practice achieving 99.95% uptime'] },
      ],
      education: [{ id: '1', institution: 'Stanford University', degree: 'Master of Science', field: 'Computer Science', startDate: '2006', endDate: '2008' }],
      skills: ['Engineering Leadership', 'Organizational Design', 'Technical Strategy', 'Agile at Scale', 'SRE/DevOps', 'Recruiting', 'Budget Management', 'Product Strategy', 'Board Presentation', 'M&A Technical Due Diligence'],
      certifications: [],
      templateId: 'corporate',
    },
  },
  {
    id: 'marketing-senior-1',
    title: 'VP of Marketing',
    industry: 'Marketing/Sales',
    experienceLevel: 'senior',
    description: 'Marketing leader with brand building and demand gen expertise',
    highlights: ['Grew pipeline from $10M to $80M', 'Built marketing team of 25', 'Rebranded 3 companies'],
    atsScore: 91,
    templateId: 'startup',
    resumeData: {
      contactInfo: { fullName: 'Jennifer Walsh', email: 'j.walsh@email.com', phone: '(555) 222-6789', location: 'Austin, TX' },
      summary: 'Strategic marketing leader with 10+ years of experience driving brand awareness, demand generation, and revenue growth for B2B SaaS companies. Expert in building marketing teams and executing data-driven campaigns.',
      experience: [
        { id: '1', company: 'SaaSGrowth Corp', position: 'VP of Marketing', startDate: 'Aug 2022', endDate: 'Present', current: true, description: 'Leading all marketing functions', achievements: ['Grew marketing-sourced pipeline from $10M to $80M annually', 'Built and led marketing team of 25 across brand, demand gen, and content', 'Executed company rebrand resulting in 60% increase in brand awareness'] },
        { id: '2', company: 'TechBrand Inc.', position: 'Director of Marketing', startDate: 'Apr 2018', endDate: 'Jul 2022', current: false, description: 'Marketing leadership for mid-market SaaS', achievements: ['Launched ABM program generating $15M in enterprise pipeline', 'Increased organic traffic by 300% through content strategy'] },
      ],
      education: [{ id: '1', institution: 'University of Texas at Austin', degree: 'MBA', field: 'Marketing', startDate: '2014', endDate: '2016' }],
      skills: ['Brand Strategy', 'Demand Generation', 'ABM', 'Content Marketing', 'Team Leadership', 'Marketing Analytics', 'Budget Management', 'Product Marketing', 'PR/Communications', 'MarTech Stack'],
      certifications: [],
      templateId: 'startup',
    },
  },
  {
    id: 'engineering-entry-1',
    title: 'Civil Engineer',
    industry: 'Engineering',
    experienceLevel: 'entry',
    description: 'Recent civil engineering graduate with internship experience',
    highlights: ['EIT certified', 'AutoCAD & Revit proficient', 'Infrastructure project experience'],
    atsScore: 85,
    templateId: 'minimal',
    resumeData: {
      contactInfo: { fullName: 'Kevin Patel', email: 'k.patel@email.com', phone: '(555) 323-7890', location: 'Houston, TX' },
      summary: 'EIT-certified civil engineer with internship experience in infrastructure design, site development, and construction management. Proficient in AutoCAD, Revit, and civil engineering analysis software.',
      experience: [
        { id: '1', company: 'Metro Infrastructure Partners', position: 'Civil Engineer I', startDate: 'Jul 2025', endDate: 'Present', current: true, description: 'Infrastructure design and construction oversight', achievements: ['Designed drainage systems for 3 residential developments', 'Managed submittals and RFIs for $5M bridge rehabilitation project', 'Conducted site inspections ensuring compliance with city codes'] },
        { id: '2', company: 'City of Houston', position: 'Engineering Intern', startDate: 'May 2024', endDate: 'Jun 2025', current: false, description: 'Public works engineering support', achievements: ['Assisted in design review of $20M stormwater improvement project', 'Created AutoCAD drawings for 10+ municipal infrastructure projects'] },
      ],
      education: [{ id: '1', institution: 'Rice University', degree: 'Bachelor of Science', field: 'Civil Engineering', startDate: '2021', endDate: '2025', gpa: '3.5' }],
      skills: ['AutoCAD', 'Revit', 'Civil 3D', 'HEC-RAS', 'Site Design', 'Structural Analysis', 'Stormwater Management', 'Construction Management', 'Project Scheduling', 'Technical Writing'],
      certifications: [{ id: '1', name: 'Engineer in Training (EIT)', issuer: 'Texas Board of PE', date: '2025' }],
      templateId: 'minimal',
    },
  },
  {
    id: 'education-senior-1',
    title: 'School Principal',
    industry: 'Education',
    experienceLevel: 'senior',
    description: 'Transformational school leader improving outcomes across districts',
    highlights: ['Raised test scores by 25%', 'Led school of 800+ students', 'Secured $2M in grants'],
    atsScore: 88,
    templateId: 'classic',
    resumeData: {
      contactInfo: { fullName: 'Dr. William Carter', email: 'w.carter@email.com', phone: '(555) 424-8901', location: 'Charlotte, NC' },
      summary: 'Transformational school leader with 15 years in education, including 8 years in administration. Proven track record of improving student outcomes, building inclusive school cultures, and securing funding for innovative programs.',
      experience: [
        { id: '1', company: 'Charlotte-Mecklenburg Schools', position: 'Principal', startDate: 'Jul 2020', endDate: 'Present', current: true, description: 'Leading K-8 school of 800+ students', achievements: ['Raised standardized test scores by 25% over 3 years', 'Secured $2M in federal and state grants for STEM programs', 'Reduced chronic absenteeism by 40% through community partnerships'] },
        { id: '2', company: 'Wake County Public Schools', position: 'Assistant Principal', startDate: 'Aug 2016', endDate: 'Jun 2020', current: false, description: 'School operations and instructional leadership', achievements: ['Led professional development for 60-person teaching staff', 'Implemented PBIS framework reducing disciplinary incidents by 50%'] },
      ],
      education: [{ id: '1', institution: 'UNC Charlotte', degree: 'Doctor of Education', field: 'Educational Leadership', startDate: '2016', endDate: '2020' }],
      skills: ['Instructional Leadership', 'Budget Management', 'Staff Development', 'Community Engagement', 'Data-Driven Decision Making', 'Grant Writing', 'Curriculum Design', 'Special Education', 'Crisis Management', 'Strategic Planning'],
      certifications: [{ id: '1', name: 'NC Principal License', issuer: 'NC DPI', date: '2016' }],
      templateId: 'classic',
    },
  },
  {
    id: 'design-entry-1',
    title: 'Graphic Designer',
    industry: 'Creative/Design',
    experienceLevel: 'entry',
    description: 'Visual storyteller with strong branding and illustration skills',
    highlights: ['Award-winning portfolio', 'Agency experience', 'Brand identity specialist'],
    atsScore: 80,
    templateId: 'portfolio',
    resumeData: {
      contactInfo: { fullName: 'Olivia Turner', email: 'o.turner@email.com', phone: '(555) 525-9012', location: 'Portland, OR', portfolio: 'oliviaturner.co' },
      summary: 'Creative graphic designer with a keen eye for typography, color theory, and visual storytelling. Experienced in brand identity design, digital marketing assets, and print production.',
      experience: [
        { id: '1', company: 'Pixel & Co. Agency', position: 'Graphic Designer', startDate: 'Feb 2025', endDate: 'Present', current: true, description: 'Design for diverse client portfolio', achievements: ['Designed brand identities for 10+ startups and small businesses', 'Created social media campaigns reaching 2M+ impressions', 'Won AIGA local chapter award for packaging design'] },
        { id: '2', company: 'Freelance', position: 'Graphic Designer', startDate: 'Jun 2024', endDate: 'Jan 2025', current: false, description: 'Independent design work', achievements: ['Built client base of 15 recurring clients', 'Designed marketing materials for 3 product launches'] },
      ],
      education: [{ id: '1', institution: 'Pacific Northwest College of Art', degree: 'Bachelor of Fine Arts', field: 'Graphic Design', startDate: '2020', endDate: '2024' }],
      skills: ['Adobe Photoshop', 'Adobe Illustrator', 'InDesign', 'Figma', 'Brand Identity', 'Typography', 'Print Design', 'Social Media Design', 'Packaging Design', 'Motion Graphics'],
      certifications: [],
      templateId: 'portfolio',
    },
  },
  {
    id: 'hr-entry-1',
    title: 'Recruiting Coordinator',
    industry: 'HR/Recruiting',
    experienceLevel: 'entry',
    description: 'Organized recruiting coordinator streamlining hiring processes',
    highlights: ['Coordinated 200+ interviews', 'Reduced time-to-schedule by 50%', 'Improved candidate experience'],
    atsScore: 84,
    templateId: 'compact',
    resumeData: {
      contactInfo: { fullName: 'Taylor Reed', email: 't.reed@email.com', phone: '(555) 626-0123', location: 'Minneapolis, MN' },
      summary: 'Detail-oriented recruiting coordinator with 1.5 years of experience supporting high-volume technical hiring. Skilled in interview scheduling, candidate communication, and ATS management.',
      experience: [
        { id: '1', company: 'TalentHub Tech', position: 'Recruiting Coordinator', startDate: 'Sep 2024', endDate: 'Present', current: true, description: 'Supporting recruiting team of 8 for engineering and product roles', achievements: ['Coordinated 200+ interviews monthly across 5 time zones', 'Reduced time-to-schedule from 5 days to 2.5 days', 'Implemented candidate feedback surveys improving NPS by 30 points'] },
        { id: '2', company: 'StaffRight Agency', position: 'HR Assistant', startDate: 'Jan 2024', endDate: 'Aug 2024', current: false, description: 'HR administrative support', achievements: ['Processed onboarding for 50+ new hires', 'Maintained ATS data accuracy at 99%'] },
      ],
      education: [{ id: '1', institution: 'University of Minnesota', degree: 'Bachelor of Arts', field: 'Human Resources', startDate: '2020', endDate: '2024' }],
      skills: ['Interview Scheduling', 'Greenhouse ATS', 'Candidate Communication', 'Onboarding', 'Google Workspace', 'Calendar Management', 'Data Entry', 'Event Planning', 'LinkedIn Recruiting', 'Employer Branding'],
      certifications: [],
      templateId: 'compact',
    },
  },
  {
    id: 'legal-senior-1',
    title: 'General Counsel',
    industry: 'Legal',
    experienceLevel: 'senior',
    description: 'In-house legal leader managing enterprise-level legal operations',
    highlights: ['Managed $10M legal budget', 'Closed $5B in deals', 'Built legal team of 15'],
    atsScore: 91,
    templateId: 'corporate',
    resumeData: {
      contactInfo: { fullName: 'Patricia Moore', email: 'p.moore@email.com', phone: '(555) 727-1234', location: 'Chicago, IL' },
      summary: 'Seasoned General Counsel with 14 years of experience in corporate law, regulatory compliance, and enterprise risk management. Expert in M&A, IP protection, and building high-performing legal teams.',
      experience: [
        { id: '1', company: 'GlobalTech Industries', position: 'General Counsel', startDate: 'May 2019', endDate: 'Present', current: true, description: 'Chief legal officer for $2B technology conglomerate', achievements: ['Managed $10M legal budget and team of 15 attorneys and paralegals', 'Advised on $5B+ in M&A transactions and strategic partnerships', 'Reduced outside counsel spend by 35% through insourcing strategy'] },
        { id: '2', company: 'Baker McKenzie LLP', position: 'Senior Associate', startDate: 'Sep 2012', endDate: 'Apr 2019', current: false, description: 'Corporate and technology transactions practice', achievements: ['Served as lead associate on 20+ M&A transactions', 'Developed IP licensing framework adopted as firm template'] },
      ],
      education: [{ id: '1', institution: 'University of Chicago Law School', degree: 'Juris Doctor', field: 'Law', startDate: '2009', endDate: '2012' }],
      skills: ['Corporate Law', 'M&A', 'Regulatory Compliance', 'IP Law', 'Contract Negotiation', 'Risk Management', 'Team Leadership', 'Board Advisory', 'Litigation Management', 'Data Privacy (GDPR/CCPA)'],
      certifications: [{ id: '1', name: 'Bar Admission - IL, NY', issuer: 'State Bar', date: '2012' }],
      templateId: 'corporate',
    },
  },
  {
    id: 'hospitality-mid-1',
    title: 'Restaurant General Manager',
    industry: 'Hospitality',
    experienceLevel: 'mid',
    description: 'Restaurant leader driving revenue growth and guest experience',
    highlights: ['Increased revenue 30%', '4.8/5 Yelp rating', 'Managed 40-person team'],
    atsScore: 83,
    templateId: 'swiss',
    resumeData: {
      contactInfo: { fullName: 'Carlos Mendez', email: 'c.mendez@email.com', phone: '(555) 828-2345', location: 'San Diego, CA' },
      summary: 'Experienced restaurant general manager with 6 years in food & beverage operations. Proven track record of increasing revenue, maintaining high guest satisfaction, and building strong teams.',
      experience: [
        { id: '1', company: 'Pacific Coast Dining Group', position: 'General Manager', startDate: 'Mar 2023', endDate: 'Present', current: true, description: 'Managing upscale casual restaurant with $4M annual revenue', achievements: ['Increased annual revenue by 30% through menu innovation and marketing', 'Maintained 4.8/5 Yelp rating with 500+ reviews', 'Reduced food waste by 25% through inventory optimization'] },
        { id: '2', company: 'Taste Kitchen & Bar', position: 'Assistant General Manager', startDate: 'Jun 2020', endDate: 'Feb 2023', current: false, description: 'Supporting operations for high-volume restaurant', achievements: ['Managed 40-person team across FOH and BOH', 'Implemented POS system reducing order errors by 60%'] },
      ],
      education: [{ id: '1', institution: 'San Diego State University', degree: 'Bachelor of Science', field: 'Hospitality & Tourism Management', startDate: '2016', endDate: '2020' }],
      skills: ['Restaurant Operations', 'P&L Management', 'Staff Training', 'Menu Development', 'Inventory Management', 'Health & Safety Compliance', 'Guest Relations', 'Toast POS', 'Marketing', 'Vendor Relations'],
      certifications: [{ id: '1', name: 'ServSafe Manager', issuer: 'National Restaurant Association', date: '2023' }],
      templateId: 'swiss',
    },
  },
  {
    id: 'cs-mid-1',
    title: 'Customer Success Manager',
    industry: 'Customer Service',
    experienceLevel: 'mid',
    description: 'Strategic CSM driving retention and expansion revenue',
    highlights: ['$5M portfolio managed', '120% NRR achieved', 'Built CSM playbook'],
    atsScore: 87,
    templateId: 'modern',
    resumeData: {
      contactInfo: { fullName: 'Rachel Torres', email: 'r.torres@email.com', phone: '(555) 929-3456', location: 'Denver, CO' },
      summary: 'Strategic customer success manager with 4 years of experience driving retention, expansion, and advocacy for B2B SaaS products. Expert in building scalable CS processes and delivering measurable business outcomes.',
      experience: [
        { id: '1', company: 'CloudPlatform Inc.', position: 'Senior Customer Success Manager', startDate: 'Jan 2024', endDate: 'Present', current: true, description: 'Managing enterprise customer portfolio', achievements: ['Managed $5M ARR portfolio with 120% net revenue retention', 'Built and documented CSM playbook adopted by 12-person team', 'Drove 15 customer case studies and 8 G2 reviews'] },
        { id: '2', company: 'DataSync Solutions', position: 'Customer Success Manager', startDate: 'Mar 2022', endDate: 'Dec 2023', current: false, description: 'Mid-market customer success', achievements: ['Achieved 95% gross retention across 60-account portfolio', 'Increased product adoption by 40% through training programs'] },
      ],
      education: [{ id: '1', institution: 'University of Colorado Boulder', degree: 'Bachelor of Science', field: 'Business', startDate: '2018', endDate: '2022' }],
      skills: ['Customer Success', 'Account Management', 'Retention Strategy', 'Upselling/Cross-selling', 'Gainsight', 'Salesforce', 'QBR Facilitation', 'Onboarding', 'Data Analysis', 'Stakeholder Management'],
      certifications: [{ id: '1', name: 'Certified Customer Success Manager', issuer: 'SuccessHacker', date: '2023' }],
      templateId: 'modern',
    },
  },
  {
    id: 'finance-entry-1',
    title: 'Junior Accountant',
    industry: 'Finance',
    experienceLevel: 'entry',
    description: 'Detail-oriented accounting graduate with internship experience',
    highlights: ['CPA exam eligible', 'QuickBooks & SAP proficient', 'Zero audit discrepancies'],
    atsScore: 86,
    templateId: 'minimal',
    resumeData: {
      contactInfo: { fullName: 'Daniel Kim', email: 'd.kim@email.com', phone: '(555) 030-4567', location: 'Philadelphia, PA' },
      summary: 'Detail-oriented accounting professional with internship experience in public accounting and corporate finance. CPA exam eligible with strong proficiency in financial reporting, tax preparation, and audit support.',
      experience: [
        { id: '1', company: 'Precision Accounting Group', position: 'Staff Accountant', startDate: 'Jul 2025', endDate: 'Present', current: true, description: 'General accounting and financial reporting', achievements: ['Prepared monthly financial statements for 12 clients with zero discrepancies', 'Processed 200+ journal entries monthly ensuring GAAP compliance', 'Assisted in year-end audit preparation for $50M revenue client'] },
        { id: '2', company: 'Deloitte', position: 'Audit Intern', startDate: 'Jan 2025', endDate: 'Jun 2025', current: false, description: 'Financial audit internship', achievements: ['Supported audit procedures for 4 mid-market clients', 'Performed substantive testing for accounts receivable and inventory'] },
      ],
      education: [{ id: '1', institution: 'Temple University', degree: 'Bachelor of Science', field: 'Accounting', startDate: '2021', endDate: '2025', gpa: '3.6' }],
      skills: ['Financial Reporting', 'GAAP', 'Tax Preparation', 'QuickBooks', 'SAP', 'Excel (Advanced)', 'Audit Support', 'Account Reconciliation', 'Payroll Processing', 'General Ledger'],
      certifications: [{ id: '1', name: 'CPA Exam Eligible', issuer: 'PA State Board', date: '2025' }],
      templateId: 'minimal',
    },
  },
];
