export const sampleJobs = [
  {
    title: 'Frontend Engineer',
    company: 'TechCorp',
    location: 'Remote',
    job_type: 'full-time',
    salary_range: '$90,000 - $130,000',
    description: 'We are looking for a skilled Frontend Engineer to join our product team. You will build and maintain responsive web applications using React, TypeScript, and modern CSS frameworks. Collaborate with designers and backend engineers to deliver seamless user experiences.',
    requirements: '3+ years of experience with React and TypeScript\nProficiency in HTML, CSS, and responsive design\nExperience with state management (Redux, Zustand, or similar)\nFamiliarity with REST APIs and GraphQL\nStrong problem-solving skills and attention to detail',
    is_saved: true,
  },
  {
    title: 'Product Designer',
    company: 'DesignStudio',
    location: 'New York, NY',
    job_type: 'full-time',
    salary_range: '$85,000 - $120,000',
    description: 'DesignStudio is seeking a Product Designer to lead end-to-end design for our SaaS platform. You will conduct user research, create wireframes and prototypes, and work closely with engineering to ship polished features.',
    requirements: '2+ years of product design experience\nProficiency in Figma or Sketch\nStrong portfolio demonstrating UX thinking\nExperience with design systems\nExcellent communication and collaboration skills',
    is_saved: true,
  },
  {
    title: 'Backend Developer',
    company: 'CloudScale',
    location: 'San Francisco, CA',
    job_type: 'contract',
    salary_range: '$70 - $90/hr',
    description: 'CloudScale needs a Backend Developer to design and implement scalable microservices. You will work with Node.js, PostgreSQL, and cloud infrastructure (AWS/GCP) to support our growing platform.',
    requirements: '4+ years backend development experience\nStrong knowledge of Node.js and PostgreSQL\nExperience with Docker and Kubernetes\nFamiliarity with CI/CD pipelines\nUnderstanding of security best practices',
    is_saved: true,
  },
  {
    title: 'Marketing Manager',
    company: 'GrowthLab',
    location: 'Chicago, IL',
    job_type: 'full-time',
    salary_range: '$75,000 - $95,000',
    description: 'GrowthLab is hiring a Marketing Manager to drive our B2B marketing strategy. You will plan and execute campaigns across email, social, and paid channels, analyze performance metrics, and optimize conversion funnels.',
    requirements: '3+ years of B2B marketing experience\nProficiency with marketing automation tools (HubSpot, Mailchimp)\nStrong analytical skills and data-driven mindset\nExcellent copywriting and content creation abilities\nExperience managing budgets and reporting ROI',
    is_saved: true,
  },
  {
    title: 'Data Analyst Intern',
    company: 'DataVault',
    location: 'Remote',
    job_type: 'internship',
    salary_range: '$25/hr',
    description: 'DataVault is offering a paid internship for aspiring data analysts. You will assist in cleaning and analyzing large datasets, creating dashboards, and presenting insights to stakeholders.',
    requirements: 'Currently pursuing a degree in Data Science, Statistics, or related field\nBasic proficiency in SQL and Python\nFamiliarity with data visualization tools (Tableau, Power BI)\nStrong attention to detail\nEager to learn and grow in a fast-paced environment',
    is_saved: true,
  },
];
