import type { ResumeData, TemplateInfo } from '@/types/resume';

export const templates: TemplateInfo[] = [
  {
    id: 'wiseresume-classic',
    name: 'WiseResume Classic',
    description: 'Crimson two-page Letter layout with ATS-friendly sections',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'modern',
    name: 'Modern',
    description: 'Clean design with accent colors',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'classic',
    name: 'Classic',
    description: 'Traditional professional layout',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'minimal',
    name: 'Minimal',
    description: 'Simple and elegant design',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'professional',
    name: 'Professional',
    description: 'Corporate-friendly template',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'developer',
    name: 'Developer',
    description: 'Code-inspired tech resume',
    atsScore: 'high',
    category: 'tech',
  },
  {
    id: 'creative',
    name: 'Creative',
    description: 'Bold sidebar with accents',
    atsScore: 'medium',
    category: 'creative',
  },
  {
    id: 'executive',
    name: 'Executive',
    description: 'Elegant serif typography',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'compact',
    name: 'Compact',
    description: 'Dense layout for entry-level',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'academic',
    name: 'Academic',
    description: 'Research-focused CV layout',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'healthcare',
    name: 'Healthcare',
    description: 'Clean medical professional',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'sales',
    name: 'Sales',
    description: 'Metrics-driven achievements',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'elegant',
    name: 'Elegant',
    description: 'Refined aesthetic design',
    atsScore: 'medium',
    category: 'creative',
  },
  // --- Industry templates ---
  {
    id: 'banking',
    name: 'Banking',
    description: 'Conservative finance industry standard',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'consulting',
    name: 'Consulting',
    description: 'Strategy-focused consulting layout',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'federal',
    name: 'Government',
    description: 'Government & public sector format',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'legal',
    name: 'Legal',
    description: 'Law firm & judicial standard',
    atsScore: 'high',
    category: 'professional',
  },
  {
    id: 'marketing',
    name: 'Marketing',
    description: 'Brand-forward creative marketing',
    atsScore: 'medium',
    category: 'creative',
  },
  {
    id: 'designer',
    name: 'Designer',
    description: 'Visual portfolio sidebar layout',
    atsScore: 'medium',
    category: 'creative',
  },
  {
    id: 'portfolio',
    name: 'Portfolio',
    description: 'Project-centric showcase layout',
    atsScore: 'medium',
    category: 'creative',
  },
  {
    id: 'data-science',
    name: 'Data Science',
    description: 'Analytics & ML focused layout',
    atsScore: 'high',
    category: 'tech',
  },
  {
    id: 'devops',
    name: 'DevOps',
    description: 'Infrastructure & CI/CD focused',
    atsScore: 'high',
    category: 'tech',
  },
  {
    id: 'product',
    name: 'Product',
    description: 'Product management & strategy',
    atsScore: 'high',
    category: 'tech',
  },
  {
    id: 'clean',
    name: 'Clean',
    description: 'Ultra-minimal whitespace design',
    atsScore: 'high',
    category: 'minimalist',
  },
  {
    id: 'swiss',
    name: 'Swiss',
    description: 'International typographic style',
    atsScore: 'high',
    category: 'minimalist',
  },
  // --- 2026 Creative Templates ---
  {
    id: 'bento',
    name: 'Bento',
    description: 'Modular card-grid layout, 2026 style',
    atsScore: 'high',
    category: 'creative',
  },
  {
    id: 'brutalist',
    name: 'Brutalist',
    description: 'Bold black borders, offset shadow header',
    atsScore: 'high',
    category: 'creative',
  },
  {
    id: 'bold-type',
    name: 'Bold Type',
    description: 'Oversized black header, strong typography',
    atsScore: 'high',
    category: 'creative',
  },
];

export const atsScoreDescriptions: Record<string, string> = {
  high: 'This template\'s layout is optimized for ATS parsing — clean structure, no graphics or tables that block scanners. This measures layout readability only, not your resume\'s keyword match or content quality.',
  medium: 'Some design elements in this template may affect parsing in certain ATS systems. Layout readability is good but not fully optimized. This does not measure keyword match or content quality.',
  low: 'This visually creative template may have reduced ATS parsability due to its design. Best for roles where you submit directly to a recruiter. This does not measure keyword match or content quality.',
};

export const atsScoreColors: Record<string, string> = {
  high: 'bg-success/20 text-success border-success/30',
  medium: 'bg-warning/20 text-warning border-warning/30',
  low: 'bg-purple-100 text-purple-700 border-purple-200 dark:bg-purple-950/40 dark:text-purple-300 dark:border-purple-800/40',
};

export const atsScoreLabels: Record<string, string> = {
  high: 'ATS Layout: Optimized',
  medium: 'ATS Layout: Good',
  low: 'ATS Layout: Creative',
};

export const sampleResumeData = {
  basics: {
    name: 'Magdy Saber',
    location: 'Cairo, Egypt',
    phone: '+201111113041',
    emails: ['magdy.saber@outlook.com', 'contact@magdysaber.com'],
    profiles: {
      linkedin: { username: 'magdy-saber', url: 'https://www.linkedin.com/in/magdy-saber/' },
      github: { username: 'iammagdy', url: 'https://github.com/iammagdy' },
      portfolio: { label: 'magdysaber.com', url: 'https://magdysaber.com' },
    },
  },
  contactInfo: {
    fullName: 'Magdy Saber',
    email: 'magdy.saber@outlook.com',
    email2: 'contact@magdysaber.com',
    phone: '+201111113041',
    location: 'Cairo, Egypt',
    linkedin: 'https://www.linkedin.com/in/magdy-saber/',
    github: 'https://github.com/iammagdy',
    portfolio: 'https://magdysaber.com',
  },
  summary: 'Versatile operations, customer experience, and technical leader with 15+ years across telecom, aviation, IT, retail, sales, and HR. Proven record of leading high-performing teams, optimizing service delivery, and driving operational efficiency and customer satisfaction. Also a hands-on builder of AI-augmented web apps with Python, React, and AWS.',
  coreCompetencies: {
    'Leadership & Operations': ['Team Leadership', 'Operations Management', 'Performance Management', 'Process Improvement', 'Operational Efficiency', 'Strategic Planning', 'Project Management'],
    'Customer Experience': ['Customer Service Management', 'CSAT', 'SLAs', 'Escalation Management', 'Customer Retention', 'Service Delivery', 'Call Center Operations'],
    'Sales & Retail Management': ['Store Management', 'Retail Operations', 'Inventory Management', 'POS Systems', 'Visual Merchandising', 'P&L', 'Sales Targets', 'Loss Prevention', 'Account Management'],
    'IT & Technical': ['IT Infrastructure', 'Network Management', 'System Administration', 'Technical Support', 'Troubleshooting', 'Security', 'System Availability'],
    'Software & Data': ['Python', 'TypeScript', 'React', 'REST APIs', 'AWS', 'Docker', 'Agile', 'Data Analysis', 'Product Management'],
    'HR & Recruitment': ['Talent Acquisition', 'Recruitment & Onboarding', 'HRIS', 'Payroll', 'Applicant Tracking Systems (ATS)', 'Employee Relations'],
  },
  experience: [
    {
      id: '1',
      company: 'The Wise Cloud',
      account: 'Self-employed',
      position: 'AI Products Developer',
      startDate: '2025-09',
      endDate: 'Present',
      current: true,
      description: '',
      achievements: ['Build and ship end-to-end SaaS products from concept to launch using AI tools, Python, React, and AWS.', 'Maintain scalable web applications and cloud IT infrastructure (Docker, Kubernetes) for reliability and performance.'],
    },
    {
      id: '2',
      company: 'Concentrix',
      account: 'Verizon',
      position: 'Customer Care Team Lead',
      startDate: '2025-12',
      endDate: '2026-04',
      current: false,
      description: '',
      achievements: ['Led a 14-rep customer care team supporting Verizon telecom accounts across 50+ key accounts.', 'Drove CSAT, SLA adherence, and operational efficiency via Salesforce and Zendesk CRM; owned coaching and escalation management.'],
    },
    {
      id: '3',
      company: 'Etihad Airways',
      position: 'Corporate & Guest Transport Supervisor',
      startDate: '2025-04',
      endDate: '2025-12',
      current: false,
      description: '',
      achievements: ['Supervised and optimized corporate and guest transport operations for seamless service delivery.', 'Led a team on technical issue resolution, improving response times and service uptime.'],
    },
    {
      id: '4',
      company: 'Teleperformance',
      account: 'Etihad Airways',
      position: 'Airline Service Coordinator',
      startDate: '2024-09',
      endDate: '2025-04',
      current: false,
      description: '',
      achievements: ['Coordinated airline service operations as liaison between passengers, ground staff, and flight crews.', 'Resolved complex, time-sensitive disruptions using reservation systems to high service standards.'],
    },
    {
      id: '5',
      company: 'e& Egypt (Etisalat)',
      position: 'Senior Sales Supervisor (Store Manager)',
      startDate: '2022-07',
      endDate: '2024-05',
      current: false,
      description: '',
      achievements: ['Managed daily operations of an Etisalat retail store as acting Store Manager: sales floor, inventory, POS, and visual merchandising.', 'Led and coached a retail sales team to exceed sales targets while driving customer experience and retention.', 'Owned store P&L, stock control, and loss prevention, ensuring operational efficiency and compliance.'],
    },
    {
      id: '6',
      company: 'White Whale',
      position: 'HR Administrator',
      startDate: '2021-01',
      endDate: '2022-07',
      current: false,
      description: '',
      achievements: ['Administered HR for 100+ employees: onboarding, payroll, HRIS, and employee relations.', 'Optimized HR processes and ensured labor-law compliance, improving employee experience.'],
    },
    {
      id: '7',
      company: 'White Whale',
      position: 'Recruitment Specialist',
      startDate: '2020-03',
      endDate: '2021-01',
      current: false,
      description: '',
      achievements: ['Managed full-cycle recruitment and talent acquisition with hiring managers.', 'Used Applicant Tracking Systems (ATS) to streamline sourcing and selection.'],
    },
    {
      id: '8',
      company: 'e& Emirates (Etisalat)',
      position: 'Customer Care Supervisor',
      startDate: '2017-01',
      endDate: '2018-09',
      current: false,
      description: '',
      achievements: ['Led a telecom customer care team, optimizing service delivery, CSAT, and KPI adherence.', 'Owned team performance, training, and resolution of complex escalations.'],
    },
    {
      id: '9',
      company: 'TE Data',
      position: 'IT Administrator',
      startDate: '2014-01',
      endDate: '2016-10',
      current: false,
      description: '',
      achievements: ['Administered IT infrastructure and systems for 100+ users, ensuring security and availability.', 'Managed network operations and strategic IT solutions for business continuity.'],
    },
    {
      id: '10',
      company: 'TE Data',
      position: 'IT Support',
      startDate: '2012-09',
      endDate: '2013-12',
      current: false,
      description: '',
      achievements: ['Provided technical support and maintenance for IT infrastructure and end-users.', 'Improved productivity through efficient IT service delivery for a major ISP.'],
    },
    {
      id: '11',
      company: 'Link ADSL',
      position: 'Senior Technical Support Specialist',
      startDate: '2008-08',
      endDate: '2012-08',
      current: false,
      description: '',
      achievements: ['Delivered technical support for internet connectivity and hardware/software troubleshooting.', 'Escalation point for complex issues; mentored junior technicians on best practices.'],
    },
  ],
  education: [
    {
      id: '1',
      institution: 'AAST - Arab Academy for Science & Technology',
      degree: '',
      field: 'Human Resources',
      startDate: '2026',
      endDate: 'Present',
    },
    {
      id: '2',
      institution: 'Cairo University',
      degree: '',
      field: 'Software Engineering',
      startDate: '2024',
      endDate: '2026',
    },
    {
      id: '3',
      institution: 'Machinfy',
      degree: '',
      field: 'Data Science',
      startDate: '2021',
      endDate: '2022',
    },
    {
      id: '4',
      institution: 'Zagazig University',
      degree: 'BA',
      field: 'Media & Journalism',
      startDate: '2015',
      endDate: '2019',
    },
  ],
  skills: ['Team Leadership', 'Operations Management', 'Customer Service Management', 'React', 'AWS', 'Python'],
  certifications: [],
  projects: [
    {
      id: '1',
      name: 'WiseResume',
      role: 'Founder & Developer',
      url: 'https://wiseresume.app',
      description: 'AI resume editor with job-match scoring, gap analysis, and ATS-friendly templates for any role.',
      technologies: ['Python', 'Django', 'React', 'AWS', 'PostgreSQL', 'spaCy', 'Transformers', 'NLP'],
      startDate: '',
      endDate: '',
    },
    {
      id: '2',
      name: 'WiseHire',
      role: 'Founder & Developer',
      url: 'https://wiseresume.app/enterprises',
      description: 'AI hiring console that screens candidates, writes job descriptions, and builds interview scorecards.',
      technologies: ['React', 'TypeScript', 'AWS', 'CRM & ATS integrations'],
      startDate: '',
      endDate: '',
    },
    {
      id: '3',
      name: 'WiseQuran',
      role: 'Founder & Developer',
      url: 'https://quran.thewise.cloud',
      description: 'Offline-first PWA for Quran reading, azkar, and daily prayer tracking.',
      technologies: ['Angular', 'Ionic', 'PWA', 'Service Workers', 'IndexedDB'],
      startDate: '',
      endDate: '',
    },
    {
      id: '4',
      name: 'WiseHumanize',
      role: 'Founder & Developer',
      url: 'https://humanize.thewise.cloud',
      description: 'AI writing assistant that turns AI-generated drafts into natural, human-sounding text.',
      technologies: ['Python', 'NLP', 'Transformers', 'React', 'Next.js'],
      startDate: '',
      endDate: '',
    },
    {
      id: '5',
      name: 'The Wise Cloud',
      role: 'Founder & Developer',
      url: 'https://thewise.cloud',
      description: 'Cloud-native platform and umbrella suite hosting the Wise products on scalable microservices.',
      technologies: ['AWS', 'Docker', 'Kubernetes', 'Redis', 'MongoDB', 'GraphQL', 'Next.js'],
      startDate: '',
      endDate: '',
    },
  ],
  templateId: 'wiseresume-classic',
} satisfies ResumeData & { basics: NonNullable<ClassicSampleExtras['basics']>; coreCompetencies: Record<string, string[]> };

interface ClassicSampleExtras {
  basics?: {
    name: string;
    location: string;
    phone: string;
    emails: string[];
    profiles: {
      linkedin: { username: string; url: string };
      github: { username: string; url: string };
      portfolio: { label: string; url: string };
    };
  };
}
