import { createRequire } from 'node:module';
import { describe, expect, it, vi, beforeEach } from 'vitest';

const require = createRequire(import.meta.url);
const adminDevkit = require('../../../appwrite-hubs/admin-devkit-data/src/main.js');
const emailService = require('../../../appwrite-hubs/email-service/src/main.js');
const adminEmail = require('../../../appwrite-hubs/admin-email/src/main.js');

describe('Admin Password Reset Link Flow & Security Contracts', () => {
  const originalEnv = process.env;

  beforeEach(() => {
    process.env = { ...originalEnv };
    process.env.EMAIL_SERVICE_INTERNAL_HMAC_SECRET = 'test_internal_secret_key_999';
    process.env.APPWRITE_API_KEY = 'test_api_key_888';
    process.env.PASSWORD_RESET_OTP_SECRET = 'test_otp_secret_777';
    process.env.RESEND_API_KEY = 'mock_resend_key_123';
    process.env.FRONTEND_URL = 'https://wiseresume.app';
  });

  it('admin-devkit-data rejects unauthenticated send-admin-password-reset-link requests', async () => {
    const resJson = vi.fn();
    const res = { json: resJson };
    const req = { headers: {} };
    const log = vi.fn();
    const error = vi.fn();

    await adminDevkit({
      req,
      res,
      log,
      error,
      body: { action: 'send-admin-password-reset-link', target_user_id: 'user_123' },
    });

    expect(resJson).toHaveBeenCalledWith(
      expect.objectContaining({
        success: false,
        code: 'DEVKIT_UNAUTHORIZED',
        error: 'DevKit token is missing, invalid, or expired.',
      }),
      401
    );
  });

  it('email-service rejects direct browser calls to send-admin-password-reset-link', async () => {
    const resJson = vi.fn();
    const res = { json: resJson };
    const bodyPayload = { action: 'send-admin-password-reset-link', target_user_id: 'usr_1' };
    const req = { method: 'POST', headers: {}, body: bodyPayload };
    const log = vi.fn();
    const error = vi.fn();

    await emailService({
      req,
      res,
      log,
      error,
      body: bodyPayload,
    });

    expect(resJson).toHaveBeenCalledWith(
      expect.objectContaining({
        error: expect.stringContaining('Direct caller access to admin password reset link is deprecated'),
      }),
      401
    );
  });

  it('admin-email rejects real send_password_reset action with explicit directive', async () => {
    const resJson = vi.fn();
    const res = { json: resJson };
    const log = vi.fn();
    const error = vi.fn();

    const crypto = require('crypto');
    const base64url = (str: string) => Buffer.from(str).toString('base64').replace(/=/g, '').replace(/\+/g, '-').replace(/\//g, '_');
    const payload = { purpose: 'devkit', exp: Date.now() + 60000 };
    const encoded = base64url(JSON.stringify(payload));
    const sig = crypto.createHmac('sha256', process.env.APPWRITE_API_KEY).update(encoded).digest('base64url');
    const signedToken = `${encoded}.${sig}`;

    const bodyPayload = { module: 'email-actions', action: 'send_password_reset', target_email: 'user@example.com' };
    const req = { method: 'POST', body: bodyPayload, headers: { authorization: `Bearer ${signedToken}` } };

    await adminEmail({
      req,
      res,
      log,
      error,
    });

    expect(resJson).toHaveBeenCalledWith(
      expect.objectContaining({
        success: false,
        error: expect.stringContaining('Password reset links are generated by admin-devkit-data'),
      }),
      500
    );
  });

  it('email-service internal-send-admin-password-reset-link verifies signature and uses wiseresume.app reset route', () => {
    const { signInternalRequest } = adminDevkit._test;
    const { verifyInternalRequestSignature } = emailService._test;

    const payload = {
      target_user_id: 'usr_target_777',
      target_email: 'user@example.com',
      actor_user_id: 'usr_admin_001',
    };

    const { timestamp, signature } = signInternalRequest(payload);

    const validBody = {
      action: 'internal-send-admin-password-reset-link',
      timestamp,
      target_user_id: payload.target_user_id,
      target_email: payload.target_email,
      actor_user_id: payload.actor_user_id,
      signature,
    };

    expect(verifyInternalRequestSignature(validBody)).toBe(true);
  });

  it('fails closed when EMAIL_SERVICE_INTERNAL_HMAC_SECRET is missing', () => {
    delete process.env.EMAIL_SERVICE_INTERNAL_HMAC_SECRET;
    const { getInternalHmacSecret: getAdminSecret, signInternalRequest } = adminDevkit._test;
    const { verifyInternalRequestSignature } = emailService._test;

    expect(() => getAdminSecret()).toThrow('EMAIL_SERVICE_INTERNAL_HMAC_SECRET is not configured');
    expect(() => signInternalRequest({ target_user_id: 'u1', target_email: 'test@example.com' })).toThrow(
      'EMAIL_SERVICE_INTERNAL_HMAC_SECRET is not configured'
    );
    expect(verifyInternalRequestSignature({ timestamp: Date.now(), target_user_id: 'u1', target_email: 'test@example.com', signature: 'sig' })).toBe(false);
  });
});
