import { useState } from 'react';
import { Download, ChevronDown, ChevronUp, ShieldCheck, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { cn } from '@/lib/utils';
import type { MaskResult } from '@/hooks/wisehire/useMaskCVs';

interface MaskedCVCardProps {
  result: MaskResult;
}

const FIELD_COLOURS: Record<string, string> = {
  NAME: 'bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400',
  EMAIL: 'bg-orange-100 text-orange-700 dark:bg-orange-900/30 dark:text-orange-400',
  PHONE: 'bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400',
  ADDRESS: 'bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400',
  'DATE OF BIRTH': 'bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400',
  NATIONALITY: 'bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400',
  GENDER: 'bg-pink-100 text-pink-700 dark:bg-pink-900/30 dark:text-pink-400',
  'PROFILE LINK': 'bg-indigo-100 text-indigo-700 dark:bg-indigo-900/30 dark:text-indigo-400',
  PHOTO: 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300',
};

function highlightRedactions(text: string): React.ReactNode[] {
  const parts = text.split(/(\[[^\]]+\])/g);
  return parts.map((part, i) => {
    if (/^\[.+\]$/.test(part)) {
      return (
        <mark
          key={i}
          className="bg-yellow-200 dark:bg-yellow-800/50 text-yellow-900 dark:text-yellow-200 rounded px-0.5 font-mono text-xs font-semibold not-italic"
        >
          {part}
        </mark>
      );
    }
    return <span key={i}>{part}</span>;
  });
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function buildMaskedHTML(result: MaskResult): string {
  const highlighted = escapeHtml(result.maskedText).replace(/\[([^\]]+)\]/g, (_, label) => {
    return `<mark class="redacted" data-field="${escapeHtml(label)}">[${escapeHtml(label)}]</mark>`;
  });
  const escaped = highlighted.replace(/\n/g, '<br>');
  const redactedList = result.redactedFields.map((f) => `<span class="badge">${escapeHtml(f)}</span>`).join(' ');
  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${escapeHtml(result.label)} – Anonymised CV</title>
<style>
  body{font-family:Georgia,serif;max-width:750px;margin:40px auto;padding:0 24px;color:#1a202c;line-height:1.75;background:#fff}
  h1{font-size:1.25rem;font-weight:700;margin-bottom:4px;color:#1e40af}
  .meta{font-size:.8rem;color:#64748b;margin-bottom:20px}
  .redacted-tags{margin-bottom:24px}
  .badge{display:inline-block;margin:2px 4px 2px 0;padding:1px 7px;border-radius:999px;background:#fef9c3;color:#854d0e;font-size:.72rem;font-weight:600;font-family:monospace;border:1px solid #fde68a}
  hr{border:none;border-top:1px solid #e2e8f0;margin:20px 0}
  .cv-body{font-size:.9rem;line-height:1.8;color:#374151}
  mark.redacted{background:#fef08a;color:#713f12;border-radius:3px;padding:0 3px;font-family:monospace;font-size:.82em;font-weight:700;border:1px solid #fde047}
  .footer{margin-top:40px;font-size:.72rem;color:#94a3b8;text-align:center;border-top:1px solid #e2e8f0;padding-top:16px}
  @media print{body{margin:20px;padding:0}}
</style>
</head>
<body>
<h1>${escapeHtml(result.label)}</h1>
<div class="meta">Source file: ${escapeHtml(result.filename)} &nbsp;·&nbsp; Generated by WiseHire CV Masking</div>
${result.redactedFields.length > 0 ? `<div class="redacted-tags"><strong style="font-size:.8rem;color:#475569">Redacted fields:</strong><br>${redactedList}</div>` : ''}
<hr>
<div class="cv-body">${escaped}</div>
<div class="footer">This document has been anonymised for bias-free candidate review. Original PII has been removed and replaced with labelled placeholders.</div>
</body>
</html>`;
}

export function MaskedCVCard({ result }: MaskedCVCardProps) {
  const [expanded, setExpanded] = useState(false);

  function handleDownload() {
    const html = buildMaskedHTML(result);
    const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${result.label.replace(' ', '_')}_masked.html`;
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="rounded-xl border bg-card overflow-hidden">
      {/* Header */}
      <div className="px-5 py-4 flex items-start justify-between gap-3 flex-wrap">
        <div className="flex items-center gap-3 min-w-0">
          <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-400 font-bold text-sm">
            {result.label.split(' ')[1] ?? '?'}
          </div>
          <div className="min-w-0">
            <p className="font-semibold text-sm">{result.label}</p>
            <p className="text-xs text-muted-foreground truncate flex items-center gap-1">
              <FileText className="h-3 w-3 shrink-0" />
              {result.filename}
            </p>
          </div>
        </div>
        <Button size="sm" variant="outline" onClick={handleDownload} className="gap-1.5 shrink-0">
          <Download className="h-3.5 w-3.5" />
          Download HTML
        </Button>
      </div>

      {/* Redacted fields */}
      {result.redactedFields.length > 0 && (
        <div className="px-5 pb-3 flex flex-wrap gap-1.5">
          <span className="flex items-center gap-1 text-xs text-muted-foreground mr-1">
            <ShieldCheck className="h-3.5 w-3.5 text-green-500" />
            Redacted:
          </span>
          {result.redactedFields.map((field) => (
            <Badge
              key={field}
              variant="secondary"
              className={cn('text-[11px] px-1.5 py-0.5 font-medium', FIELD_COLOURS[field] ?? 'bg-slate-100 text-slate-700 dark:bg-slate-800 dark:text-slate-300')}
            >
              {field}
            </Badge>
          ))}
        </div>
      )}

      {result.redactedFields.length === 0 && (
        <div className="px-5 pb-3">
          <p className="text-xs text-muted-foreground italic">No PII detected in this document.</p>
        </div>
      )}

      {/* Preview toggle */}
      <div className="border-t">
        <button
          className="w-full flex items-center justify-between px-5 py-2.5 text-xs font-medium text-muted-foreground hover:bg-muted/30 transition-colors"
          onClick={() => setExpanded((o) => !o)}
        >
          <span>Preview masked text</span>
          {expanded ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />}
        </button>

        {expanded && (
          <div className="px-5 pb-5">
            <div className="max-h-72 overflow-y-auto rounded-lg bg-muted/40 dark:bg-slate-800/50 p-3 text-xs leading-relaxed whitespace-pre-wrap font-mono border">
              {highlightRedactions(result.maskedText)}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
