/**
 * Client-side PDF export for candidate briefs.
 * Uses browser print API with an injected print stylesheet.
 */

import type { CandidateBrief } from '@/hooks/wisehire/useBriefs';

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

export function exportBriefToPdf(brief: CandidateBrief, candidateName: string) {
  const printWindow = window.open('', '_blank', 'width=800,height=600');
  if (!printWindow) {
    alert('Please allow pop-ups to export the brief as PDF.');
    return;
  }

  const scoreColor = brief.match_score !== null
    ? brief.match_score >= 80 ? '#059669'
      : brief.match_score >= 60 ? '#d97706'
      : '#dc2626'
    : '#64748b';

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>Candidate Brief — ${escapeHtml(candidateName)}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; font-size: 13px; color: #1e293b; padding: 32px; line-height: 1.6; }
    h1 { font-size: 22px; font-weight: 800; color: #1d4ed8; margin-bottom: 4px; }
    .meta { font-size: 11px; color: #64748b; margin-bottom: 24px; }
    .score { display: inline-flex; align-items: center; gap: 8px; margin-bottom: 24px; }
    .score-ring { width: 56px; height: 56px; border-radius: 50%; border: 4px solid ${scoreColor}; display: flex; align-items: center; justify-content: center; font-size: 16px; font-weight: 800; color: ${scoreColor}; }
    .score-label { font-size: 12px; color: #64748b; }
    section { margin-bottom: 20px; }
    h2 { font-size: 13px; font-weight: 700; text-transform: uppercase; letter-spacing: 0.05em; color: #475569; border-bottom: 1px solid #e2e8f0; padding-bottom: 4px; margin-bottom: 10px; }
    ul { padding-left: 20px; }
    li { margin-bottom: 4px; color: #334155; }
    .notes { background: #f8fafc; border-left: 3px solid #1d4ed8; padding: 10px 14px; border-radius: 0 6px 6px 0; color: #334155; }
    .footer { margin-top: 32px; font-size: 10px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 12px; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>${escapeHtml(candidateName)}</h1>
  <p class="meta">WiseHire Candidate Brief · ${escapeHtml(brief.role?.title ?? 'Unknown Role')} · Generated ${escapeHtml(new Date(brief.created_at).toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' }))}</p>

  <div class="score">
    <div class="score-ring">${brief.match_score ?? '—'}</div>
    <div>
      <div style="font-weight:700;font-size:15px">Match Score</div>
      <div class="score-label">${brief.match_score !== null ? (brief.match_score >= 80 ? 'Strong match' : brief.match_score >= 60 ? 'Moderate match' : 'Weak match') : 'Not scored'}</div>
    </div>
  </div>

  <section>
    <h2>Strengths</h2>
    <ul>${(brief.strengths ?? []).map((s) => `<li>${escapeHtml(s)}</li>`).join('')}</ul>
  </section>

  <section>
    <h2>Concerns</h2>
    <ul>${(brief.concerns ?? []).map((c) => `<li>${escapeHtml(c)}</li>`).join('')}</ul>
  </section>

  <section>
    <h2>Interview Questions</h2>
    <ol style="padding-left:20px">${(brief.interview_questions ?? []).map((q) => `<li style="margin-bottom:6px">${escapeHtml(q)}</li>`).join('')}</ol>
  </section>

  ${brief.employment_notes ? `<section>
    <h2>Hiring Notes</h2>
    <div class="notes">${escapeHtml(brief.employment_notes)}</div>
  </section>` : ''}

  <div class="footer">Generated by WiseHire · thewise.cloud · ${brief.ai_model_used ? `AI: ${escapeHtml(brief.ai_model_used)}` : ''}</div>

  <script>window.onload = function() { window.print(); window.onafterprint = function() { window.close(); }; };<\/script>
</body>
</html>`;

  printWindow.document.write(html);
  printWindow.document.close();
}
