import { useParams, Link } from 'react-router-dom';
import { ClipboardList, ExternalLink } from 'lucide-react';
import { ScorecardView } from '@/components/wisehire/scorecard/ScorecardView';
import { ScorecardSkeleton } from '@/components/wisehire/scorecard/ScorecardSkeleton';
import { Button } from '@/components/ui/button';
import { usePublicScorecard } from '@/hooks/wisehire/useScorecards';

export default function PublicScorecardPage() {
  const { shareToken } = useParams<{ shareToken: string }>();
  const { data: scorecard, isLoading, isError } = usePublicScorecard(shareToken);

  return (
    <div className="min-h-[100dvh] bg-[#f0f5ff] dark:bg-[#00061a]">
      {/* Header */}
      <header className="border-b bg-white dark:bg-[#000d2e] px-4 py-3">
        <div className="max-w-3xl mx-auto flex items-center justify-between gap-4">
          <div className="flex items-center gap-2">
            <ClipboardList className="h-5 w-5 text-blue-600 dark:text-blue-400" />
            <span className="font-bold text-blue-700 dark:text-blue-300 text-sm">
              WiseHire · Scorecard
            </span>
          </div>
          <Button variant="outline" size="sm" asChild className="gap-2 text-xs">
            <Link to="/?for=companies">
              <ExternalLink className="h-3 w-3" />
              Learn about WiseHire
            </Link>
          </Button>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-4 py-8">
        {isLoading && <ScorecardSkeleton />}

        {(isError || (!isLoading && !scorecard)) && (
          <div className="text-center py-20 space-y-3">
            <ClipboardList className="mx-auto h-12 w-12 text-muted-foreground/40" />
            <h2 className="text-lg font-semibold">Scorecard not found</h2>
            <p className="text-sm text-muted-foreground">
              This link may have been revoked or doesn't exist.
            </p>
          </div>
        )}

        {!isLoading && scorecard && (
          <div className="rounded-xl border bg-white dark:bg-[#000d2e] p-6 shadow-sm">
            <ScorecardView scorecard={scorecard} />
          </div>
        )}
      </main>

      <footer className="border-t text-center py-4 text-xs text-muted-foreground">
        Generated by{' '}
        <a
          href="/?for=companies"
          className="text-blue-600 dark:text-blue-400 hover:underline"
        >
          WiseHire
        </a>
      </footer>
    </div>
  );
}
