/**
 * /act-as?t=<otp>
 *
 * Claims a one-time impersonation token generated by the DevKit "Act As" button,
 * stores the resulting session in sessionStorage (tab-local), then redirects the
 * user to "/dashboard" so they see the impersonated user's dashboard.
 *
 * Guards against React StrictMode double-firing via a useRef flag.
 */
import { useEffect, useRef, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { Loader2, UserX, AlertCircle } from 'lucide-react';
import { startImpersonation } from '@/lib/impersonationStore';

async function claimToken(otp: string): Promise<{ access_token: string; user_id: string; email: string; expires_at: number }> {
  const res = await fetch(`/api/fn/admin-impersonate-claim?t=${encodeURIComponent(otp)}`, { method: 'GET' });
  const data = await res.json() as { success: boolean; access_token?: string; user_id?: string; email?: string; expires_at?: number; error?: string };
  if (!res.ok || !data.success) throw new Error(data.error ?? `Server error ${res.status}`);
  return { access_token: data.access_token!, user_id: data.user_id!, email: data.email!, expires_at: data.expires_at! };
}

export default function ActAs() {
  const [params] = useSearchParams();
  const navigate = useNavigate();
  const [error, setError] = useState<string | null>(null);
  const claimed = useRef(false);

  useEffect(() => {
    // StrictMode guard — only claim the OTP once per tab lifetime
    if (claimed.current) return;
    claimed.current = true;

    const otp = params.get('t');
    if (!otp) { setError('Missing token in URL.'); return; }

    claimToken(otp)
      .then(({ access_token, user_id, email, expires_at }) => {
        startImpersonation(access_token, user_id, email, expires_at, true);
        navigate('/dashboard', { replace: true });
      })
      .catch((err: unknown) => {
        setError(err instanceof Error ? err.message : String(err));
      });
  }, []);

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <div className="flex flex-col items-center gap-4 max-w-sm text-center p-8">
          <AlertCircle className="w-12 h-12 text-destructive" />
          <h1 className="text-xl font-semibold">Could not start Act As session</h1>
          <p className="text-sm text-muted-foreground">{error}</p>
          <p className="text-xs text-muted-foreground">
            This link can only be used once and expires after 2 minutes. Go back to the DevKit and click "Act As" again.
          </p>
          <button onClick={() => window.close()} className="text-sm underline text-muted-foreground hover:text-foreground">
            Close this tab
          </button>
        </div>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background">
      <div className="flex flex-col items-center gap-4">
        <div className="flex items-center gap-3">
          <UserX className="w-8 h-8 text-red-500" />
          <Loader2 className="w-6 h-6 animate-spin text-muted-foreground" />
        </div>
        <p className="text-sm text-muted-foreground">Starting Act As session…</p>
      </div>
    </div>
  );
}
