-- Legacy Profiles Schema Documentation (as of 2026-03-14)
-- This file serves as a reference for the 42-column monolithic table before normalization.

CREATE TABLE public.profiles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL UNIQUE,
  full_name TEXT,
  avatar_url TEXT,
  username TEXT UNIQUE,
  bio TEXT,
  job_title TEXT,
  industry TEXT,
  career_level TEXT,
  location TEXT,
  linkedin_url TEXT,
  github_url TEXT,
  twitter_url TEXT,
  website_url TEXT,
  contact_email TEXT,
  portfolio_theme TEXT,
  portfolio_bio TEXT,
  portfolio_sections JSONB,
  portfolio_meta_title TEXT,
  portfolio_meta_description TEXT,
  portfolio_layout TEXT,
  portfolio_accent_color TEXT,
  portfolio_font TEXT,
  portfolio_style TEXT,
  portfolio_extras JSONB,
  portfolio_sync_mode TEXT,
  portfolio_resume_id UUID,
  portfolio_enabled BOOLEAN DEFAULT true,
  github_projects_cache JSONB,
  github_last_synced TIMESTAMPTZ,
  views INTEGER DEFAULT 0,
  last_active_at TIMESTAMPTZ,
  login_streak INTEGER DEFAULT 0,
  last_login_date DATE,
  hired_at TIMESTAMPTZ,
  open_to_work BOOLEAN DEFAULT false,
  availability_headline TEXT,
  digest_enabled BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now(),
  is_deleted BOOLEAN DEFAULT false,
  deleted_at TIMESTAMPTZ
);

COMMENT ON TABLE public.profiles IS 'God table holding identity, settings, socials, and gamification.';
