// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/landing-variants/FeatureFirst.tsx": () => import("../components/mockups/landing-variants/FeatureFirst.tsx"),
  "./components/mockups/landing-variants/SplitStage.tsx": () => import("../components/mockups/landing-variants/SplitStage.tsx"),
  "./components/mockups/landing-variants/StepNarrative.tsx": () => import("../components/mockups/landing-variants/StepNarrative.tsx")
};
