import type { QRTemplate } from './qr-types';

export const QR_TEMPLATES: QRTemplate[] = [
  {
    id: 'classic',
    name: 'Classic',
    emoji: '⬛',
    foregroundColor: '#000000',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'square', roundness: 0 },
    eyes: { shape: 'square', innerShape: 'square' },
  },
  {
    id: 'wiseresume',
    name: 'WiseResume',
    emoji: '🟣',
    foregroundColor: '#a855f7',
    backgroundColor: '#18181b',
    gradient: { enabled: true, type: 'radial', from: '#a855f7', to: '#ec4899', angle: 0 },
    moduleStyle: { shape: 'rounded', roundness: 0.6 },
    eyes: { shape: 'extra-rounded', innerShape: 'dot', outerColor: '#a855f7', innerColor: '#ec4899' },
    logo: { enabled: true, sizePercent: 25, safeZone: true },
  },
  {
    id: 'linkedin',
    name: 'LinkedIn',
    emoji: '🔵',
    foregroundColor: '#0A66C2',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'rounded', roundness: 0.5 },
    eyes: { shape: 'extra-rounded', innerShape: 'dot', outerColor: '#0A66C2', innerColor: '#0A66C2' },
  },
  {
    id: 'instagram',
    name: 'Instagram',
    emoji: '📸',
    foregroundColor: '#E1306C',
    backgroundColor: '#ffffff',
    gradient: { enabled: true, type: 'linear', from: '#F58529', to: '#DD2A7B', angle: 135 },
    moduleStyle: { shape: 'dots', roundness: 1 },
    eyes: { shape: 'dot', innerShape: 'dot', outerColor: '#833AB4', innerColor: '#F58529' },
  },
  {
    id: 'youtube',
    name: 'YouTube',
    emoji: '🔴',
    foregroundColor: '#FF0000',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'rounded', roundness: 0.4 },
    eyes: { shape: 'extra-rounded', innerShape: 'dot', outerColor: '#FF0000', innerColor: '#FF0000' },
  },
  {
    id: 'twitter',
    name: 'X / Twitter',
    emoji: '🖤',
    foregroundColor: '#000000',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'classy-rounded', roundness: 0.5 },
    eyes: { shape: 'extra-rounded', innerShape: 'dot', outerColor: '#000000', innerColor: '#000000' },
  },
  {
    id: 'facebook',
    name: 'Facebook',
    emoji: '🟦',
    foregroundColor: '#1877F2',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'rounded', roundness: 0.4 },
    eyes: { shape: 'extra-rounded', innerShape: 'square', outerColor: '#1877F2', innerColor: '#1877F2' },
  },
  {
    id: 'github',
    name: 'GitHub',
    emoji: '🐙',
    foregroundColor: '#333333',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'square', roundness: 0 },
    eyes: { shape: 'square', innerShape: 'square', outerColor: '#333333', innerColor: '#333333' },
  },
  {
    id: 'pinterest',
    name: 'Pinterest',
    emoji: '📌',
    foregroundColor: '#E60023',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'dots', roundness: 1 },
    eyes: { shape: 'dot', innerShape: 'dot', outerColor: '#E60023', innerColor: '#E60023' },
  },
  {
    id: 'maps',
    name: 'Google Maps',
    emoji: '📍',
    foregroundColor: '#34A853',
    backgroundColor: '#ffffff',
    moduleStyle: { shape: 'extra-rounded', roundness: 0.7 },
    eyes: { shape: 'extra-rounded', innerShape: 'dot', outerColor: '#34A853', innerColor: '#FBBC04' },
  },
  {
    id: 'wifi',
    name: 'WiFi',
    emoji: '📶',
    foregroundColor: '#00BCD4',
    backgroundColor: '#1a1a2e',
    moduleStyle: { shape: 'dots', roundness: 1 },
    eyes: { shape: 'dot', innerShape: 'dot', outerColor: '#00BCD4', innerColor: '#00BCD4' },
  },
  {
    id: 'minimal',
    name: 'Minimal',
    emoji: '🤍',
    foregroundColor: '#4a4a4a',
    backgroundColor: '#f8f8f8',
    moduleStyle: { shape: 'square', roundness: 0.1 },
    eyes: { shape: 'square', innerShape: 'square', outerColor: '#4a4a4a', innerColor: '#4a4a4a' },
  },
];
