-- Private storage bucket used by `_shared/pdfRenderer.ts` to host PDFs
-- generated by `mobile-api` (action=export-pdf). Uploaded path is
-- `<user_id>/<kind>/<ts>-<title>.pdf`; downloads use 1-hour signed URLs
-- minted server-side by the edge function.
insert into storage.buckets (id, name, public)
values ('exports', 'exports', false)
on conflict (id) do nothing;

drop policy if exists "exports_owner_read" on storage.objects;
create policy "exports_owner_read"
on storage.objects for select
to authenticated
using (
  bucket_id = 'exports'
  and (storage.foldername(name))[1] = auth.uid()::text
);

-- Writes are service-role-only (mobile-api uses the service client to
-- upload), so no INSERT policy for authenticated users is required.
