-- WiseHire Phase 1 — Migration 3: wisehire_invites
-- Stores HMAC-SHA256 signed invite tokens generated by admin.
-- Tokens expire after 72 hours. Single-use (used_at set after successful sign-up).
-- Admin-only access via service role key.

CREATE TABLE IF NOT EXISTS public.wisehire_invites (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  token           TEXT NOT NULL UNIQUE,
  token_signature TEXT NOT NULL,
  recipient_email TEXT NOT NULL,
  created_by      UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  expires_at      TIMESTAMPTZ NOT NULL,
  used_at         TIMESTAMPTZ,
  is_revoked      BOOLEAN NOT NULL DEFAULT false
);

CREATE INDEX IF NOT EXISTS wisehire_invites_token_idx
  ON public.wisehire_invites (token);

CREATE INDEX IF NOT EXISTS wisehire_invites_email_idx
  ON public.wisehire_invites (recipient_email);

ALTER TABLE public.wisehire_invites ENABLE ROW LEVEL SECURITY;

-- No user-facing RLS policies. Service role key bypasses RLS for admin functions.
