/**
 * Authenticated Supabase client pointing to the correct project.
 *
 * This file creates its OWN client using the hardcoded constants from
 * supabaseConstants.ts (project jnsfmkzgxsviuthaqlyy) and automatically
 * injects the Clerk JWT on every request via a global fetch interceptor.
 *
 * All runtime code should import from this file, NOT from client.ts
 * (which is auto-generated by Lovable Cloud and points to a different project).
 */
import { createClient } from '@supabase/supabase-js';
import { SUPABASE_URL, SUPABASE_ANON_KEY } from '@/lib/supabaseConstants';
import { getClerkSupabaseToken } from '@/lib/clerkSupabase';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
  },
  global: {
    fetch: async (input: RequestInfo | URL, init?: RequestInit) => {
      const headers = new Headers(init?.headers);

      // Inject Clerk JWT if available (makes RLS auth.uid() work)
      try {
        const token = await getClerkSupabaseToken();
        if (token) {
          headers.set('Authorization', `Bearer ${token}`);
        }
      } catch {
        // No token available — request proceeds with anon key only
      }

      // Always include the apikey header
      if (!headers.has('apikey')) {
        headers.set('apikey', SUPABASE_ANON_KEY);
      }

      return fetch(input, { ...init, headers });
    },
  },
});

// Backward-compatible exports
export const supabaseConfig = { url: SUPABASE_URL };
export { SUPABASE_URL, SUPABASE_ANON_KEY as SUPABASE_PUBLISHABLE_KEY };
