import { test, expect } from '@playwright/test';

const BASE_URL = "https://wiseresume.app";

test.describe("Production QA Verification", () => {
  // Use the pre-authenticated storageState generated by generate-qa-session.cjs
  test.use({
    baseURL: BASE_URL,
    storageState: 'tests/e2e/.auth/qa-user.json',
  });

  test("Verify Dashboard, AI Privacy Consent, and Abort Flow", async ({ page }) => {
    page.on("console", msg => {
      console.log(`[BROWSER CONSOLE] ${msg.type()}: ${msg.text()}`);
    });
    page.on("pageerror", err => {
      console.error(`[BROWSER ERROR] ${err.message}`);
    });

    // Intercept and mock Appwrite get-subscription executions to return a Pro plan
    await page.route('**/functions/**/executions', async route => {
      const url = route.request().url();
      if (url.includes('get-subscription') || url.includes('coupons')) {
        console.log(`[MOCK FUNCTION] Mocking get-subscription response for Pro plan...`);
        const mockResponse = {
          status: "completed",
          responseStatusCode: 200,
          responseBody: JSON.stringify({
            status: "success",
            data: {
              plan: "pro",
              effective_plan: "pro",
              status: "active",
              trial_plan: null,
              trial_expires_at: null,
              coupon_code: null
            }
          }),
          stdout: "",
          stderr: ""
        };
        await route.fulfill({
          status: 200,
          contentType: 'application/json',
          body: JSON.stringify(mockResponse),
          headers: {
            'access-control-allow-origin': 'https://wiseresume.app',
            'access-control-allow-credentials': 'true'
          }
        });
      } else {
        await route.continue();
      }
    });

    // 1. Open Dashboard directly (pre-authenticated and onboarding bypassed via storageState)
    console.log("Navigating to dashboard...");
    await page.goto("/dashboard", { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(4000);

    // Verify user is on dashboard
    await expect(page).toHaveURL(/\/dashboard/, { timeout: 10000 });
    console.log("Confirmed on dashboard.");

    // Dismiss cookie consent if present
    const cookieBtn = page.locator("button:has-text('Accept'), button:has-text('قبول')").first();
    if (await cookieBtn.isVisible({ timeout: 2000 }).catch(() => false)) {
      console.log("Dismissing cookie consent...");
      await cookieBtn.click();
      await page.waitForTimeout(1000);
    }

    // 2. Open Create Resume dialog via ?action=create URL parameter
    console.log("Opening Create Resume dialog via URL action param...");
    await page.goto("/dashboard?action=create", { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(3000);

    const dialog = page.locator("[role='dialog']");
    await dialog.waitFor({ state: "visible", timeout: 15000 });
    console.log("Create Resume dialog is open.");

    console.log("Clicking Start from Scratch...");
    await dialog.getByText("Start from Scratch").click();
    await page.waitForTimeout(1500);

    console.log("Clicking experience level Senior...");
    await dialog.getByText("Senior", { exact: false }).first().click();
    await page.waitForTimeout(1000);

    console.log("Clicking Continue from intake step...");
    await dialog.getByRole("button", { name: "Continue" }).click();
    await page.waitForTimeout(1500);

    console.log("Clicking Continue from template selection step...");
    await dialog.getByRole("button", { name: "Continue" }).click();
    await page.waitForTimeout(1500);

    console.log("Filling resume title...");
    await dialog.getByLabel("Resume Title").fill("E2E Test Resume Title");

    console.log("Clicking Create button...");
    await dialog.getByRole("button", { name: "Create" }).click();

    console.log("Waiting for editor redirect...");
    await page.waitForURL(/\/editor/, { timeout: 30000 });
    await page.waitForTimeout(4000);
    console.log("Confirmed on editor page.");

    // 3. AI Data Processing Notice should automatically open on first load
    console.log("Checking AI Data Processing Notice visibility...");
    const consentHeader = page
      .locator("h2:has-text('AI Data Processing Notice'), [role='dialog'] h2:has-text('AI Data Processing Notice')")
      .first();
    await expect(consentHeader).toBeVisible({ timeout: 15000 });

    console.log("Consent modal visible. Accepting...");
    const acceptBtn = page
      .locator("[role='dialog'] button:has-text('I understand, continue')")
      .first();
    await acceptBtn.click();
    
    // Wait for the consent modal to animate out
    await page.waitForTimeout(3000);
    await expect(consentHeader).not.toBeVisible();
    console.log("Consent accepted successfully.");

    // 3b. Dismiss the automatically triggered "A couple of quick questions" dialog
    console.log("Dismissing automatically triggered quick questions dialog...");
    await page.keyboard.press("Escape");
    await page.waitForTimeout(2000);

    // Ensure the dialog is closed and backdrop is gone
    const backdrop = page.locator("div.fixed.inset-0").first();
    if (await backdrop.isVisible().catch(() => false)) {
      await backdrop.waitFor({ state: "hidden", timeout: 5000 }).catch(() => {});
    }
    await page.waitForTimeout(1000);

    // 4. Open AI Resume Tailor modal (Improve with AI button in top bar)
    console.log("Opening AI Tailor modal via Improve with AI button...");
    const openTailorBtn = page
      .locator("button.editor-topbar-cta, button[aria-label='Improve with AI']")
      .first();
    await openTailorBtn.waitFor({ state: "visible", timeout: 15000 });
    await openTailorBtn.click();
    await page.waitForTimeout(2000);

    // Verify the consent notice does NOT reappear
    console.log("Verifying privacy consent is NOT re-shown...");
    await expect(consentHeader).not.toBeVisible();
    
    // Verify the AI Resume Tailor sheet is open
    const tailorTitle = page
      .locator("h2:has-text('AI Resume Tailor'), [role='dialog'] h2:has-text('AI Resume Tailor')")
      .first();
    await expect(tailorTitle).toBeVisible({ timeout: 10000 });
    console.log("PASS: AI Resume Tailor sheet opened directly.");

    // Close the tailor sheet
    console.log("Closing AI Tailor sheet...");
    await page.keyboard.press("Escape");
    await page.waitForTimeout(1000);

    // 5. Navigate back to dashboard to verify metrics cards and onboarding checklist
    console.log("Navigating back to dashboard (workspace now populated)...");
    await page.goto("/dashboard", { waitUntil: "domcontentloaded" });
    await page.waitForTimeout(4000);

    // Verify Saved Jobs metric card label
    console.log("Verifying Saved Jobs metric card...");
    const savedJobsCard = page
      .locator("button:has-text('Saved Jobs'), button:has-text('الوظائف المحفوظة')")
      .first();
    await expect(savedJobsCard).toBeVisible({ timeout: 10000 });
    const cardText = await savedJobsCard.innerText();
    console.log("Saved Jobs Card text:", cardText);
    expect(cardText.toLowerCase()).toContain("saved jobs");
    expect(cardText.toLowerCase()).not.toContain("saved resumes");

    // Verify Tailored Resumes metric card has 0 count and weekly subtext
    console.log("Verifying Tailored Resumes metric card...");
    const tailoredResumesCard = page
      .locator("button:has-text('Tailored Resumes'), button:has-text('السير الذاتية المخصصة')")
      .first();
    await expect(tailoredResumesCard).toBeVisible({ timeout: 10000 });
    const tailoredText = await tailoredResumesCard.innerText();
    console.log("Tailored Resumes Card text:", tailoredText);
    expect(tailoredText).toContain("0");
    expect(tailoredText.toLowerCase()).toContain("0 this week");

    // Verify Onboarding Checklist is visible
    console.log("Checking onboarding checklist visibility...");
    const checklistHeading = page
      .locator("p:has-text('Getting started'), p:has-text('ابدأ هنا'), p:has-text(\"You're all set!\")")
      .first();
    const checklistVisible = await checklistHeading.isVisible({ timeout: 5000 }).catch(() => false);
    if (checklistVisible) {
      console.log("PASS: Onboarding checklist is visible.");
    } else {
      console.log("INFO: Onboarding checklist not visible.");
    }

    console.log("=== ALL CHECKS PASSED ===");
  });
});
